/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest = {
  roleId: string;
  body: models.AddPermissionRequest;
};

/** @internal */
export type AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest$Outbound =
  {
    role_id: string;
    body: models.AddPermissionRequest$Outbound;
  };

/** @internal */
export const AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest$outboundSchema:
  z.ZodMiniType<
    AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest$Outbound,
    AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest
  > = z.pipe(
    z.object({
      roleId: z.string(),
      body: models.AddPermissionRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        roleId: "role_id",
      });
    }),
  );

export function addPermissionEndpointApiV1RolesRoleIdPermissionsPostRequestToJSON(
  addPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest:
    AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest,
): string {
  return JSON.stringify(
    AddPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest$outboundSchema
      .parse(addPermissionEndpointApiV1RolesRoleIdPermissionsPostRequest),
  );
}
