/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest =
  {
    eventId: number;
    documentId: string;
  };

/** @internal */
export type AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest$Outbound =
  {
    event_id: number;
    document_id: string;
  };

/** @internal */
export const AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest$outboundSchema:
  z.ZodMiniType<
    AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest$Outbound,
    AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      documentId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
        documentId: "document_id",
      });
    }),
  );

export function addDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequestToJSON(
  addDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest:
    AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest,
): string {
  return JSON.stringify(
    AddDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest$outboundSchema
      .parse(
        addDocumentToEventApiV1EventsEventIdDocumentsDocumentIdPostRequest,
      ),
  );
}
