/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest = {
  spaceId: number;
  body: models.SpaceContactCreate;
};

/** @internal */
export type AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest$Outbound = {
  space_id: number;
  body: models.SpaceContactCreate$Outbound;
};

/** @internal */
export const AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest$outboundSchema:
  z.ZodMiniType<
    AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest$Outbound,
    AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
      body: models.SpaceContactCreate$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function addContactToSpaceApiV1SpacesSpaceIdContactsPostRequestToJSON(
  addContactToSpaceApiV1SpacesSpaceIdContactsPostRequest:
    AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest,
): string {
  return JSON.stringify(
    AddContactToSpaceApiV1SpacesSpaceIdContactsPostRequest$outboundSchema.parse(
      addContactToSpaceApiV1SpacesSpaceIdContactsPostRequest,
    ),
  );
}
