/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest = {
  spaceId: number;
  body: models.AddSpaceMemberRequest;
};

/** @internal */
export type AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest$Outbound = {
  space_id: number;
  body: models.AddSpaceMemberRequest$Outbound;
};

/** @internal */
export const AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest$outboundSchema:
  z.ZodMiniType<
    AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest$Outbound,
    AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
      body: models.AddSpaceMemberRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function addSpaceMemberApiV1SpaceSpaceIdMembersPostRequestToJSON(
  addSpaceMemberApiV1SpaceSpaceIdMembersPostRequest:
    AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest,
): string {
  return JSON.stringify(
    AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest$outboundSchema.parse(
      addSpaceMemberApiV1SpaceSpaceIdMembersPostRequest,
    ),
  );
}
