/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest =
  {
    userId: string;
    roleId: string;
  };

/** @internal */
export type AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest$Outbound =
  {
    user_id: string;
    role_id: string;
  };

/** @internal */
export const AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest$outboundSchema:
  z.ZodMiniType<
    AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest$Outbound,
    AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest
  > = z.pipe(
    z.object({
      userId: z.string(),
      roleId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        userId: "user_id",
        roleId: "role_id",
      });
    }),
  );

export function assignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequestToJSON(
  assignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest:
    AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest,
): string {
  return JSON.stringify(
    AssignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest$outboundSchema
      .parse(
        assignRoleToUserEndpointApiV1ApiV1RolesUsersUserIdRolesPostRequest,
      ),
  );
}
