/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeletePlaceApiV1PlacePlaceIdDeleteRequest = {
  placeId: number;
};

/** @internal */
export type DeletePlaceApiV1PlacePlaceIdDeleteRequest$Outbound = {
  place_id: number;
};

/** @internal */
export const DeletePlaceApiV1PlacePlaceIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeletePlaceApiV1PlacePlaceIdDeleteRequest$Outbound,
    DeletePlaceApiV1PlacePlaceIdDeleteRequest
  > = z.pipe(
    z.object({
      placeId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        placeId: "place_id",
      });
    }),
  );

export function deletePlaceApiV1PlacePlaceIdDeleteRequestToJSON(
  deletePlaceApiV1PlacePlaceIdDeleteRequest:
    DeletePlaceApiV1PlacePlaceIdDeleteRequest,
): string {
  return JSON.stringify(
    DeletePlaceApiV1PlacePlaceIdDeleteRequest$outboundSchema.parse(
      deletePlaceApiV1PlacePlaceIdDeleteRequest,
    ),
  );
}
