/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest = {
  ruleId: string;
};

/** @internal */
export type DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest$Outbound = {
  rule_id: string;
};

/** @internal */
export const DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest$Outbound,
    DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest
  > = z.pipe(
    z.object({
      ruleId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        ruleId: "rule_id",
      });
    }),
  );

export function deleteRuleApiV1AutomationRulesRuleIdDeleteRequestToJSON(
  deleteRuleApiV1AutomationRulesRuleIdDeleteRequest:
    DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteRuleApiV1AutomationRulesRuleIdDeleteRequest$outboundSchema.parse(
      deleteRuleApiV1AutomationRulesRuleIdDeleteRequest,
    ),
  );
}
