/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest = {
  spaceId: number;
  roleId: string;
};

/** @internal */
export type DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest$Outbound =
  {
    space_id: number;
    role_id: string;
  };

/** @internal */
export const DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest$Outbound,
    DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
      roleId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
        roleId: "role_id",
      });
    }),
  );

export function deleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequestToJSON(
  deleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest:
    DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest$outboundSchema
      .parse(deleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest),
  );
}
