/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetTimelineApiV1EventEventIdTimelineGetSecurity = {
  permissionDependency: string;
};

export type GetTimelineApiV1EventEventIdTimelineGetRequest = {
  eventId: number;
};

/** @internal */
export type GetTimelineApiV1EventEventIdTimelineGetSecurity$Outbound = {
  PermissionDependency: string;
};

/** @internal */
export const GetTimelineApiV1EventEventIdTimelineGetSecurity$outboundSchema:
  z.ZodMiniType<
    GetTimelineApiV1EventEventIdTimelineGetSecurity$Outbound,
    GetTimelineApiV1EventEventIdTimelineGetSecurity
  > = z.pipe(
    z.object({
      permissionDependency: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        permissionDependency: "PermissionDependency",
      });
    }),
  );

export function getTimelineApiV1EventEventIdTimelineGetSecurityToJSON(
  getTimelineApiV1EventEventIdTimelineGetSecurity:
    GetTimelineApiV1EventEventIdTimelineGetSecurity,
): string {
  return JSON.stringify(
    GetTimelineApiV1EventEventIdTimelineGetSecurity$outboundSchema.parse(
      getTimelineApiV1EventEventIdTimelineGetSecurity,
    ),
  );
}

/** @internal */
export type GetTimelineApiV1EventEventIdTimelineGetRequest$Outbound = {
  event_id: number;
};

/** @internal */
export const GetTimelineApiV1EventEventIdTimelineGetRequest$outboundSchema:
  z.ZodMiniType<
    GetTimelineApiV1EventEventIdTimelineGetRequest$Outbound,
    GetTimelineApiV1EventEventIdTimelineGetRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function getTimelineApiV1EventEventIdTimelineGetRequestToJSON(
  getTimelineApiV1EventEventIdTimelineGetRequest:
    GetTimelineApiV1EventEventIdTimelineGetRequest,
): string {
  return JSON.stringify(
    GetTimelineApiV1EventEventIdTimelineGetRequest$outboundSchema.parse(
      getTimelineApiV1EventEventIdTimelineGetRequest,
    ),
  );
}
