/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetUserListApiV1UserGetRequest = {
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Prev ID
   */
  prev?: number | undefined;
};

/** @internal */
export type GetUserListApiV1UserGetRequest$Outbound = {
  limit: number;
  prev?: number | undefined;
};

/** @internal */
export const GetUserListApiV1UserGetRequest$outboundSchema: z.ZodMiniType<
  GetUserListApiV1UserGetRequest$Outbound,
  GetUserListApiV1UserGetRequest
> = z.object({
  limit: z._default(z.int(), 10),
  prev: z.optional(z.int()),
});

export function getUserListApiV1UserGetRequestToJSON(
  getUserListApiV1UserGetRequest: GetUserListApiV1UserGetRequest,
): string {
  return JSON.stringify(
    GetUserListApiV1UserGetRequest$outboundSchema.parse(
      getUserListApiV1UserGetRequest,
    ),
  );
}
