/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest = {
  eventId: number;
};

/** @internal */
export type GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest$Outbound = {
  event_id: number;
};

/** @internal */
export const GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest$outboundSchema:
  z.ZodMiniType<
    GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest$Outbound,
    GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function getEventDocumentsApiV1EventsEventIdDocumentsGetRequestToJSON(
  getEventDocumentsApiV1EventsEventIdDocumentsGetRequest:
    GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest,
): string {
  return JSON.stringify(
    GetEventDocumentsApiV1EventsEventIdDocumentsGetRequest$outboundSchema.parse(
      getEventDocumentsApiV1EventsEventIdDocumentsGetRequest,
    ),
  );
}
