/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSocialFeedApiV1EventSocialFeedGetRequest = {
  /**
   * Cursor for pagination
   */
  cursor?: string | null | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * User's current time for ranking (defaults to server time if not provided)
   */
  currentTime?: Date | null | undefined;
};

/** @internal */
export type GetSocialFeedApiV1EventSocialFeedGetRequest$Outbound = {
  cursor?: string | null | undefined;
  limit: number;
  current_time?: string | null | undefined;
};

/** @internal */
export const GetSocialFeedApiV1EventSocialFeedGetRequest$outboundSchema:
  z.ZodMiniType<
    GetSocialFeedApiV1EventSocialFeedGetRequest$Outbound,
    GetSocialFeedApiV1EventSocialFeedGetRequest
  > = z.pipe(
    z.object({
      cursor: z.optional(z.nullable(z.string())),
      limit: z._default(z.int(), 20),
      currentTime: z.optional(
        z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        currentTime: "current_time",
      });
    }),
  );

export function getSocialFeedApiV1EventSocialFeedGetRequestToJSON(
  getSocialFeedApiV1EventSocialFeedGetRequest:
    GetSocialFeedApiV1EventSocialFeedGetRequest,
): string {
  return JSON.stringify(
    GetSocialFeedApiV1EventSocialFeedGetRequest$outboundSchema.parse(
      getSocialFeedApiV1EventSocialFeedGetRequest,
    ),
  );
}
