/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest = {
  userId: string;
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Prev ID
   */
  prev?: number | undefined;
  /**
   * Sort by field
   */
  sortBy?: string | undefined;
  /**
   * Sort order
   */
  sortOrder?: string | undefined;
};

/** @internal */
export type GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest$Outbound =
  {
    user_id: string;
    limit: number;
    prev?: number | undefined;
    sort_by: string;
    sort_order: string;
  };

/** @internal */
export const GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest$outboundSchema:
  z.ZodMiniType<
    GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest$Outbound,
    GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest
  > = z.pipe(
    z.object({
      userId: z.string(),
      limit: z._default(z.int(), 10),
      prev: z.optional(z.int()),
      sortBy: z._default(z.string(), "created_at"),
      sortOrder: z._default(z.string(), "desc"),
    }),
    z.transform((v) => {
      return remap$(v, {
        userId: "user_id",
        sortBy: "sort_by",
        sortOrder: "sort_order",
      });
    }),
  );

export function getJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequestToJSON(
  getJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest:
    GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest,
): string {
  return JSON.stringify(
    GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest$outboundSchema
      .parse(getJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest),
  );
}
