/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest =
  {
    spaceId: number;
  };

/** @internal */
export type GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest$Outbound =
  {
    space_id: number;
  };

/** @internal */
export const GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest$outboundSchema:
  z.ZodMiniType<
    GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest$Outbound,
    GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function getLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequestToJSON(
  getLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest:
    GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest,
): string {
  return JSON.stringify(
    GetLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest$outboundSchema
      .parse(
        getLatestPublishedVersionApiV1PublicSpaceSpaceIdVersionsLatestGetRequest,
      ),
  );
}
