/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest = {
  eventId: number;
};

/** @internal */
export type GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest$Outbound =
  {
    event_id: number;
  };

/** @internal */
export const GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest$outboundSchema:
  z.ZodMiniType<
    GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest$Outbound,
    GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function getPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequestToJSON(
  getPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest:
    GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest,
): string {
  return JSON.stringify(
    GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest$outboundSchema
      .parse(getPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest),
  );
}
