/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetUserListApiV1UserGetSecurity = {
  permissionDependency: string;
};

export type GetUserListApiV1UserGetRequest = {
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Prev ID
   */
  prev?: number | undefined;
};

/** @internal */
export type GetUserListApiV1UserGetSecurity$Outbound = {
  PermissionDependency: string;
};

/** @internal */
export const GetUserListApiV1UserGetSecurity$outboundSchema: z.ZodMiniType<
  GetUserListApiV1UserGetSecurity$Outbound,
  GetUserListApiV1UserGetSecurity
> = z.pipe(
  z.object({
    permissionDependency: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      permissionDependency: "PermissionDependency",
    });
  }),
);

export function getUserListApiV1UserGetSecurityToJSON(
  getUserListApiV1UserGetSecurity: GetUserListApiV1UserGetSecurity,
): string {
  return JSON.stringify(
    GetUserListApiV1UserGetSecurity$outboundSchema.parse(
      getUserListApiV1UserGetSecurity,
    ),
  );
}

/** @internal */
export type GetUserListApiV1UserGetRequest$Outbound = {
  limit: number;
  prev?: number | undefined;
};

/** @internal */
export const GetUserListApiV1UserGetRequest$outboundSchema: z.ZodMiniType<
  GetUserListApiV1UserGetRequest$Outbound,
  GetUserListApiV1UserGetRequest
> = z.object({
  limit: z._default(z.int(), 10),
  prev: z.optional(z.int()),
});

export function getUserListApiV1UserGetRequestToJSON(
  getUserListApiV1UserGetRequest: GetUserListApiV1UserGetRequest,
): string {
  return JSON.stringify(
    GetUserListApiV1UserGetRequest$outboundSchema.parse(
      getUserListApiV1UserGetRequest,
    ),
  );
}
