/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest = {
  spaceId: number;
};

/** @internal */
export type GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest$Outbound = {
  space_id: number;
};

/** @internal */
export const GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest$outboundSchema:
  z.ZodMiniType<
    GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest$Outbound,
    GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function getSpaceMembersApiV1SpaceSpaceIdMembersGetRequestToJSON(
  getSpaceMembersApiV1SpaceSpaceIdMembersGetRequest:
    GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest,
): string {
  return JSON.stringify(
    GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest$outboundSchema.parse(
      getSpaceMembersApiV1SpaceSpaceIdMembersGetRequest,
    ),
  );
}
