/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest = {
  spaceId: number;
};

/** @internal */
export type GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest$Outbound =
  {
    space_id: number;
  };

/** @internal */
export const GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest$outboundSchema:
  z.ZodMiniType<
    GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest$Outbound,
    GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function getLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequestToJSON(
  getLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest:
    GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest,
): string {
  return JSON.stringify(
    GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest$outboundSchema
      .parse(getLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest),
  );
}
