/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest =
  {
    eventId: number;
  };

/** @internal */
export type GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest$Outbound =
  {
    event_id: number;
  };

/** @internal */
export const GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest$outboundSchema:
  z.ZodMiniType<
    GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest$Outbound,
    GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function getLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequestToJSON(
  getLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest:
    GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest,
): string {
  return JSON.stringify(
    GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest$outboundSchema
      .parse(
        getLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest,
      ),
  );
}
