/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest = {
  spaceId: number;
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Offset
   */
  offset?: number | undefined;
  /**
   * Sort by field
   */
  sortBy?: string | undefined;
  /**
   * Sort order (asc or desc)
   */
  sortOrder?: string | undefined;
  /**
   * Search query
   */
  search?: string | undefined;
  /**
   * Start date for filtering
   */
  startDt?: Date | null | undefined;
  /**
   * End date for filtering
   */
  endDt?: Date | null | undefined;
};

/** @internal */
export type GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest$Outbound = {
  space_id: number;
  limit: number;
  offset: number;
  sort_by: string;
  sort_order: string;
  search?: string | undefined;
  start_dt?: string | null | undefined;
  end_dt?: string | null | undefined;
};

/** @internal */
export const GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest$Outbound,
    GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
      limit: z._default(z.int(), 10),
      offset: z._default(z.int(), 0),
      sortBy: z._default(z.string(), "created_at"),
      sortOrder: z._default(z.string(), "desc"),
      search: z.optional(z.string()),
      startDt: z.optional(
        z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      ),
      endDt: z.optional(
        z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
        sortBy: "sort_by",
        sortOrder: "sort_order",
        startDt: "start_dt",
        endDt: "end_dt",
      });
    }),
  );

export function getEventsBySpaceApiV1EventSpaceSpaceIdGetRequestToJSON(
  getEventsBySpaceApiV1EventSpaceSpaceIdGetRequest:
    GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest,
): string {
  return JSON.stringify(
    GetEventsBySpaceApiV1EventSpaceSpaceIdGetRequest$outboundSchema.parse(
      getEventsBySpaceApiV1EventSpaceSpaceIdGetRequest,
    ),
  );
}
