/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetLatestPublicSpaceVersionRequest = {
  spaceId: number;
};

/** @internal */
export type GetLatestPublicSpaceVersionRequest$Outbound = {
  space_id: number;
};

/** @internal */
export const GetLatestPublicSpaceVersionRequest$outboundSchema: z.ZodMiniType<
  GetLatestPublicSpaceVersionRequest$Outbound,
  GetLatestPublicSpaceVersionRequest
> = z.pipe(
  z.object({
    spaceId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      spaceId: "space_id",
    });
  }),
);

export function getLatestPublicSpaceVersionRequestToJSON(
  getLatestPublicSpaceVersionRequest: GetLatestPublicSpaceVersionRequest,
): string {
  return JSON.stringify(
    GetLatestPublicSpaceVersionRequest$outboundSchema.parse(
      getLatestPublicSpaceVersionRequest,
    ),
  );
}
