/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PatchEventContentApiV1EventEventIdContentPatchRequest = {
  eventId: number;
  body: models.UpdateEventContentRequest;
};

/** @internal */
export type PatchEventContentApiV1EventEventIdContentPatchRequest$Outbound = {
  event_id: number;
  body: models.UpdateEventContentRequest$Outbound;
};

/** @internal */
export const PatchEventContentApiV1EventEventIdContentPatchRequest$outboundSchema:
  z.ZodMiniType<
    PatchEventContentApiV1EventEventIdContentPatchRequest$Outbound,
    PatchEventContentApiV1EventEventIdContentPatchRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      body: models.UpdateEventContentRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function patchEventContentApiV1EventEventIdContentPatchRequestToJSON(
  patchEventContentApiV1EventEventIdContentPatchRequest:
    PatchEventContentApiV1EventEventIdContentPatchRequest,
): string {
  return JSON.stringify(
    PatchEventContentApiV1EventEventIdContentPatchRequest$outboundSchema.parse(
      patchEventContentApiV1EventEventIdContentPatchRequest,
    ),
  );
}
