/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PatchEventSettingsApiV1EventEventIdSettingsPatchRequest = {
  eventId: number;
  body: models.UpdateEventSettingsRequest;
};

/** @internal */
export type PatchEventSettingsApiV1EventEventIdSettingsPatchRequest$Outbound = {
  event_id: number;
  body: models.UpdateEventSettingsRequest$Outbound;
};

/** @internal */
export const PatchEventSettingsApiV1EventEventIdSettingsPatchRequest$outboundSchema:
  z.ZodMiniType<
    PatchEventSettingsApiV1EventEventIdSettingsPatchRequest$Outbound,
    PatchEventSettingsApiV1EventEventIdSettingsPatchRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      body: models.UpdateEventSettingsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function patchEventSettingsApiV1EventEventIdSettingsPatchRequestToJSON(
  patchEventSettingsApiV1EventEventIdSettingsPatchRequest:
    PatchEventSettingsApiV1EventEventIdSettingsPatchRequest,
): string {
  return JSON.stringify(
    PatchEventSettingsApiV1EventEventIdSettingsPatchRequest$outboundSchema
      .parse(patchEventSettingsApiV1EventEventIdSettingsPatchRequest),
  );
}
