/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest =
  {
    eventId: number;
    body: models.UpdateEventIdentificationRequest;
  };

/** @internal */
export type PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest$Outbound =
  {
    event_id: number;
    body: models.UpdateEventIdentificationRequest$Outbound;
  };

/** @internal */
export const PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest$outboundSchema:
  z.ZodMiniType<
    PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest$Outbound,
    PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      body: models.UpdateEventIdentificationRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function patchEventIdentificationApiV1EventEventIdIdentificationPatchRequestToJSON(
  patchEventIdentificationApiV1EventEventIdIdentificationPatchRequest:
    PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest,
): string {
  return JSON.stringify(
    PatchEventIdentificationApiV1EventEventIdIdentificationPatchRequest$outboundSchema
      .parse(
        patchEventIdentificationApiV1EventEventIdIdentificationPatchRequest,
      ),
  );
}
