/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type PublishEventApiV1EventEventIdPublishPatchRequest = {
  eventId: number;
};

/** @internal */
export type PublishEventApiV1EventEventIdPublishPatchRequest$Outbound = {
  event_id: number;
};

/** @internal */
export const PublishEventApiV1EventEventIdPublishPatchRequest$outboundSchema:
  z.ZodMiniType<
    PublishEventApiV1EventEventIdPublishPatchRequest$Outbound,
    PublishEventApiV1EventEventIdPublishPatchRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function publishEventApiV1EventEventIdPublishPatchRequestToJSON(
  publishEventApiV1EventEventIdPublishPatchRequest:
    PublishEventApiV1EventEventIdPublishPatchRequest,
): string {
  return JSON.stringify(
    PublishEventApiV1EventEventIdPublishPatchRequest$outboundSchema.parse(
      publishEventApiV1EventEventIdPublishPatchRequest,
    ),
  );
}
