/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest =
  {
    eventId: number;
    documentId: string;
  };

/** @internal */
export type RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest$Outbound =
  {
    event_id: number;
    document_id: string;
  };

/** @internal */
export const RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest$Outbound,
    RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      documentId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
        documentId: "document_id",
      });
    }),
  );

export function removeDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequestToJSON(
  removeDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest:
    RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest,
): string {
  return JSON.stringify(
    RemoveDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest$outboundSchema
      .parse(
        removeDocumentFromEventApiV1EventsEventIdDocumentsDocumentIdDeleteRequest,
      ),
  );
}
