/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest = {
  spaceId: number;
  body: models.RollbackSpaceRequest;
};

/** @internal */
export type RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest$Outbound = {
  space_id: number;
  body: models.RollbackSpaceRequest$Outbound;
};

/** @internal */
export const RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest$outboundSchema:
  z.ZodMiniType<
    RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest$Outbound,
    RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
      body: models.RollbackSpaceRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function rollbackSpaceApiV1SpaceSpaceIdRollbackPostRequestToJSON(
  rollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest:
    RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest,
): string {
  return JSON.stringify(
    RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest$outboundSchema.parse(
      rollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest,
    ),
  );
}
