/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type SearchUsersApiV1UserSearchGetRequest = {
  /**
   * Search query for username, first_name, last_name, or email. If empty, returns first users based on limit.
   */
  q?: string | undefined;
  /**
   * Limit for pagination
   */
  limit?: number | undefined;
  /**
   * Previous ID for cursor-based pagination
   */
  prev?: number | undefined;
  /**
   * Optional organization ID to filter users within specific organization
   */
  orgId?: string | undefined;
};

/** @internal */
export type SearchUsersApiV1UserSearchGetRequest$Outbound = {
  q: string;
  limit: number;
  prev?: number | undefined;
  org_id?: string | undefined;
};

/** @internal */
export const SearchUsersApiV1UserSearchGetRequest$outboundSchema: z.ZodMiniType<
  SearchUsersApiV1UserSearchGetRequest$Outbound,
  SearchUsersApiV1UserSearchGetRequest
> = z.pipe(
  z.object({
    q: z._default(z.string(), ""),
    limit: z._default(z.int(), 10),
    prev: z.optional(z.int()),
    orgId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
    });
  }),
);

export function searchUsersApiV1UserSearchGetRequestToJSON(
  searchUsersApiV1UserSearchGetRequest: SearchUsersApiV1UserSearchGetRequest,
): string {
  return JSON.stringify(
    SearchUsersApiV1UserSearchGetRequest$outboundSchema.parse(
      searchUsersApiV1UserSearchGetRequest,
    ),
  );
}
