/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SendMessageApiV1ChatRoomIdMessagesPostRequest = {
  roomId: string;
  body: models.AppChatAdapterInputSchemasMessageSendMessageRequest;
};

/** @internal */
export type SendMessageApiV1ChatRoomIdMessagesPostRequest$Outbound = {
  room_id: string;
  body: models.AppChatAdapterInputSchemasMessageSendMessageRequest$Outbound;
};

/** @internal */
export const SendMessageApiV1ChatRoomIdMessagesPostRequest$outboundSchema:
  z.ZodMiniType<
    SendMessageApiV1ChatRoomIdMessagesPostRequest$Outbound,
    SendMessageApiV1ChatRoomIdMessagesPostRequest
  > = z.pipe(
    z.object({
      roomId: z.string(),
      body:
        models
          .AppChatAdapterInputSchemasMessageSendMessageRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        roomId: "room_id",
      });
    }),
  );

export function sendMessageApiV1ChatRoomIdMessagesPostRequestToJSON(
  sendMessageApiV1ChatRoomIdMessagesPostRequest:
    SendMessageApiV1ChatRoomIdMessagesPostRequest,
): string {
  return JSON.stringify(
    SendMessageApiV1ChatRoomIdMessagesPostRequest$outboundSchema.parse(
      sendMessageApiV1ChatRoomIdMessagesPostRequest,
    ),
  );
}
