/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest = {
  roleId: string;
  body: models.SetPermissionsRequest;
};

/** @internal */
export type SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest$Outbound =
  {
    role_id: string;
    body: models.SetPermissionsRequest$Outbound;
  };

/** @internal */
export const SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest$outboundSchema:
  z.ZodMiniType<
    SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest$Outbound,
    SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest
  > = z.pipe(
    z.object({
      roleId: z.string(),
      body: models.SetPermissionsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        roleId: "role_id",
      });
    }),
  );

export function setPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequestToJSON(
  setPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest:
    SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest,
): string {
  return JSON.stringify(
    SetPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest$outboundSchema
      .parse(setPermissionsEndpointApiV1ApiV1RolesRoleIdPermissionsPutRequest),
  );
}
