/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type TransferEventApiV1EventEventIdTransferPostRequest = {
  eventId: number;
  body: models.TransferEventRequest;
};

/** @internal */
export type TransferEventApiV1EventEventIdTransferPostRequest$Outbound = {
  event_id: number;
  body: models.TransferEventRequest$Outbound;
};

/** @internal */
export const TransferEventApiV1EventEventIdTransferPostRequest$outboundSchema:
  z.ZodMiniType<
    TransferEventApiV1EventEventIdTransferPostRequest$Outbound,
    TransferEventApiV1EventEventIdTransferPostRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      body: models.TransferEventRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function transferEventApiV1EventEventIdTransferPostRequestToJSON(
  transferEventApiV1EventEventIdTransferPostRequest:
    TransferEventApiV1EventEventIdTransferPostRequest,
): string {
  return JSON.stringify(
    TransferEventApiV1EventEventIdTransferPostRequest$outboundSchema.parse(
      transferEventApiV1EventEventIdTransferPostRequest,
    ),
  );
}
