/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest =
  {
    eventId: number;
  };

/** @internal */
export type UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest$Outbound =
  {
    event_id: number;
  };

/** @internal */
export const UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest$outboundSchema:
  z.ZodMiniType<
    UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest$Outbound,
    UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function unpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequestToJSON(
  unpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest:
    UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest,
): string {
  return JSON.stringify(
    UnpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest$outboundSchema
      .parse(
        unpublishEventVersionApiV1EventEventIdVersionsUnpublishPostRequest,
      ),
  );
}
