/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateRoomApiV1ChatRoomsRoomIdPatchRequest = {
  roomId: string;
  body: models.UpdateRoomRequest;
};

/** @internal */
export type UpdateRoomApiV1ChatRoomsRoomIdPatchRequest$Outbound = {
  room_id: string;
  body: models.UpdateRoomRequest$Outbound;
};

/** @internal */
export const UpdateRoomApiV1ChatRoomsRoomIdPatchRequest$outboundSchema:
  z.ZodMiniType<
    UpdateRoomApiV1ChatRoomsRoomIdPatchRequest$Outbound,
    UpdateRoomApiV1ChatRoomsRoomIdPatchRequest
  > = z.pipe(
    z.object({
      roomId: z.string(),
      body: models.UpdateRoomRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        roomId: "room_id",
      });
    }),
  );

export function updateRoomApiV1ChatRoomsRoomIdPatchRequestToJSON(
  updateRoomApiV1ChatRoomsRoomIdPatchRequest:
    UpdateRoomApiV1ChatRoomsRoomIdPatchRequest,
): string {
  return JSON.stringify(
    UpdateRoomApiV1ChatRoomsRoomIdPatchRequest$outboundSchema.parse(
      updateRoomApiV1ChatRoomsRoomIdPatchRequest,
    ),
  );
}
