/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest = {
  spaceId: number;
  body: models.UpdateParentRequest;
};

/** @internal */
export type UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest$Outbound = {
  space_id: number;
  body: models.UpdateParentRequest$Outbound;
};

/** @internal */
export const UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest$outboundSchema:
  z.ZodMiniType<
    UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest$Outbound,
    UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest
  > = z.pipe(
    z.object({
      spaceId: z.int(),
      body: models.UpdateParentRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        spaceId: "space_id",
      });
    }),
  );

export function updateSpaceParentApiV1SpaceSpaceIdParentPatchRequestToJSON(
  updateSpaceParentApiV1SpaceSpaceIdParentPatchRequest:
    UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest,
): string {
  return JSON.stringify(
    UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest$outboundSchema.parse(
      updateSpaceParentApiV1SpaceSpaceIdParentPatchRequest,
    ),
  );
}
