/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateEventApiV1EventEventIdPutRequest = {
  eventId: number;
  body: models.CreateEventRequest;
};

/** @internal */
export type UpdateEventApiV1EventEventIdPutRequest$Outbound = {
  event_id: number;
  body: models.CreateEventRequest$Outbound;
};

/** @internal */
export const UpdateEventApiV1EventEventIdPutRequest$outboundSchema:
  z.ZodMiniType<
    UpdateEventApiV1EventEventIdPutRequest$Outbound,
    UpdateEventApiV1EventEventIdPutRequest
  > = z.pipe(
    z.object({
      eventId: z.int(),
      body: models.CreateEventRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        eventId: "event_id",
      });
    }),
  );

export function updateEventApiV1EventEventIdPutRequestToJSON(
  updateEventApiV1EventEventIdPutRequest:
    UpdateEventApiV1EventEventIdPutRequest,
): string {
  return JSON.stringify(
    UpdateEventApiV1EventEventIdPutRequest$outboundSchema.parse(
      updateEventApiV1EventEventIdPutRequest,
    ),
  );
}
