"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class AssignRoleToUserEndpointAPIV1APIV1RolesUsersUserIDRolesPostRequestTypedDict(
    TypedDict
):
    user_id: str
    role_id: str


class AssignRoleToUserEndpointAPIV1APIV1RolesUsersUserIDRolesPostRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    role_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
