"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, UNSET_SENTINEL
from openapi.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateOnlineMeetingRequestTypedDict(TypedDict):
    title: str
    r"""Place title"""
    description: str
    r"""Place description"""
    visibility: int
    r"""Visibility level"""
    meeting_url: str
    r"""Meeting URL"""
    keywords: NotRequired[List[str]]
    r"""Keywords"""
    place_type: Literal["online_meeting"]
    r"""Place type"""


class CreateOnlineMeetingRequest(BaseModel):
    title: str
    r"""Place title"""

    description: str
    r"""Place description"""

    visibility: int
    r"""Visibility level"""

    meeting_url: str
    r"""Meeting URL"""

    keywords: Optional[List[str]] = None
    r"""Keywords"""

    place_type: Annotated[
        Annotated[
            Literal["online_meeting"], AfterValidator(validate_const("online_meeting"))
        ],
        pydantic.Field(alias="place_type"),
    ] = "online_meeting"
    r"""Place type"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["keywords"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateOnlineMeetingRequest.model_rebuild()
except NameError:
    pass
