"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .app_event_domain_entity_event_spaceinfo import (
    AppEventDomainEntityEventSpaceInfo,
    AppEventDomainEntityEventSpaceInfoTypedDict,
)
from .eventread import EventRead, EventReadTypedDict
from datetime import datetime
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class EventVersionReadTypedDict(TypedDict):
    r"""Published event version response."""

    id: int
    event_id: int
    transaction_id: int
    status: str
    title: str
    start_dt: datetime
    end_dt: datetime
    timezone: str
    r"""Timezone (IANA timezone format, e.g., 'UTC', 'America/New_York', 'Europe/London')"""
    visibility: Nullable[int]
    keywords: List[str]
    latitude: Nullable[float]
    longitude: Nullable[float]
    published_at: datetime
    published_by: str
    created_at: datetime
    updated_at: datetime
    description: NotRequired[Nullable[str]]
    address: NotRequired[Nullable[str]]
    event_metadata: NotRequired[Nullable[Dict[str, Any]]]
    spaces: NotRequired[List[AppEventDomainEntityEventSpaceInfoTypedDict]]
    documents: NotRequired[List[str]]
    timeline: NotRequired[List[EventReadTypedDict]]


class EventVersionRead(BaseModel):
    r"""Published event version response."""

    id: int

    event_id: int

    transaction_id: int

    status: str

    title: str

    start_dt: datetime

    end_dt: datetime

    timezone: str
    r"""Timezone (IANA timezone format, e.g., 'UTC', 'America/New_York', 'Europe/London')"""

    visibility: Nullable[int]

    keywords: List[str]

    latitude: Nullable[float]

    longitude: Nullable[float]

    published_at: datetime

    published_by: str

    created_at: datetime

    updated_at: datetime

    description: OptionalNullable[str] = UNSET

    address: OptionalNullable[str] = UNSET

    event_metadata: OptionalNullable[Dict[str, Any]] = UNSET

    spaces: Optional[List[AppEventDomainEntityEventSpaceInfo]] = None

    documents: Optional[List[str]] = None

    timeline: Optional[List[EventRead]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "address",
                "event_metadata",
                "spaces",
                "documents",
                "timeline",
            ]
        )
        nullable_fields = set(
            [
                "description",
                "visibility",
                "latitude",
                "longitude",
                "address",
                "event_metadata",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
