"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class EventRepeatFilterTypedDict(TypedDict):
    r"""Recurrence/repeat-based filtering options for events."""

    repeat_days: NotRequired[Nullable[List[int]]]
    r"""Filter by repeat days (0=Sunday, 1=Monday, etc.)"""
    repeat_presets: NotRequired[Nullable[List[str]]]
    r"""Filter by repeat presets (daily, weekly, monthly, etc.)"""
    is_recurring: NotRequired[Nullable[bool]]
    r"""Filter recurring vs non-recurring events"""
    timeline_preset: NotRequired[Nullable[List[str]]]
    r"""Filter by timeline preset values"""


class EventRepeatFilter(BaseModel):
    r"""Recurrence/repeat-based filtering options for events."""

    repeat_days: OptionalNullable[List[int]] = UNSET
    r"""Filter by repeat days (0=Sunday, 1=Monday, etc.)"""

    repeat_presets: OptionalNullable[List[str]] = UNSET
    r"""Filter by repeat presets (daily, weekly, monthly, etc.)"""

    is_recurring: OptionalNullable[bool] = UNSET
    r"""Filter recurring vs non-recurring events"""

    timeline_preset: OptionalNullable[List[str]] = UNSET
    r"""Filter by timeline preset values"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["repeat_days", "repeat_presets", "is_recurring", "timeline_preset"]
        )
        nullable_fields = set(
            ["repeat_days", "repeat_presets", "is_recurring", "timeline_preset"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
