"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class ExecuteRuleRequestTypedDict(TypedDict):
    r"""Request to manually execute a rule."""

    trigger_type: NotRequired[str]
    trigger_context: NotRequired[Dict[str, Any]]


class ExecuteRuleRequest(BaseModel):
    r"""Request to manually execute a rule."""

    trigger_type: Optional[str] = "MANUAL"

    trigger_context: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["trigger_type", "trigger_context"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
