"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPlaceScheduleAPIV1BookingPlacesPlaceIDScheduleGetRequestTypedDict(TypedDict):
    place_id: int
    start_date: datetime
    r"""Start date for schedule"""
    end_date: datetime
    r"""End date for schedule"""


class GetPlaceScheduleAPIV1BookingPlacesPlaceIDScheduleGetRequest(BaseModel):
    place_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    start_date: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Start date for schedule"""

    end_date: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""End date for schedule"""
