"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetWorkflowExecutionAPIV1AiWorkflowsExecutionIDGetRequestTypedDict(TypedDict):
    execution_id: str


class GetWorkflowExecutionAPIV1AiWorkflowsExecutionIDGetRequest(BaseModel):
    execution_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
