"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetEventDocumentsAPIV1EventsEventIDDocumentsGetRequestTypedDict(TypedDict):
    event_id: int


class GetEventDocumentsAPIV1EventsEventIDDocumentsGetRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
