"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetSpaceByIDAPIV1SpaceSpaceIDGetRequestTypedDict(TypedDict):
    space_id: int


class GetSpaceByIDAPIV1SpaceSpaceIDGetRequest(BaseModel):
    space_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
