"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPublishedTimelineAPIV1EventEventIDTimelinePublishedGetRequestTypedDict(
    TypedDict
):
    event_id: int


class GetPublishedTimelineAPIV1EventEventIDTimelinePublishedGetRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
