"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventanalytictotal import EventAnalyticTotal, EventAnalyticTotalTypedDict
from .placeanalytictotal import PlaceAnalyticTotal, PlaceAnalyticTotalTypedDict
from .spaceanalytictotal import SpaceAnalyticTotal, SpaceAnalyticTotalTypedDict
from openapi.types import BaseModel
from typing_extensions import TypedDict


class GetAnalyticTotalsDtoTypedDict(TypedDict):
    event: EventAnalyticTotalTypedDict
    place: PlaceAnalyticTotalTypedDict
    space: SpaceAnalyticTotalTypedDict


class GetAnalyticTotalsDto(BaseModel):
    event: EventAnalyticTotal

    place: PlaceAnalyticTotal

    space: SpaceAnalyticTotal
