"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agenttype import AgentType
from .sessionstatus import SessionStatus
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from openapi.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListSessionsAPIV1AiSessionsGetRequestTypedDict(TypedDict):
    agent_type: NotRequired[Nullable[AgentType]]
    r"""Filter by agent type"""
    status: NotRequired[Nullable[SessionStatus]]
    r"""Filter by session status"""
    limit: NotRequired[int]
    r"""Number of sessions to return"""
    offset: NotRequired[int]
    r"""Offset for pagination"""


class ListSessionsAPIV1AiSessionsGetRequest(BaseModel):
    agent_type: Annotated[
        OptionalNullable[AgentType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter by agent type"""

    status: Annotated[
        OptionalNullable[SessionStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter by session status"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Number of sessions to return"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Offset for pagination"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["agent_type", "status", "limit", "offset"])
        nullable_fields = set(["agent_type", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
