"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateeventidentificationrequest import (
    UpdateEventIdentificationRequest,
    UpdateEventIdentificationRequestTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PatchEventIdentificationAPIV1EventEventIDIdentificationPatchRequestTypedDict(
    TypedDict
):
    event_id: int
    body: UpdateEventIdentificationRequestTypedDict


class PatchEventIdentificationAPIV1EventEventIDIdentificationPatchRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        UpdateEventIdentificationRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
