"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PublishEventWithNotificationsRequestTypedDict(TypedDict):
    notify_attendees: NotRequired[bool]
    r"""Whether to notify attendees about the publication"""
    notification_channels: NotRequired[Nullable[List[str]]]
    r"""List of channels to use for notification (e.g., 'EMAIL', 'SMS', 'WHATSAPP')"""


class PublishEventWithNotificationsRequest(BaseModel):
    notify_attendees: Optional[bool] = False
    r"""Whether to notify attendees about the publication"""

    notification_channels: OptionalNullable[List[str]] = UNSET
    r"""List of channels to use for notification (e.g., 'EMAIL', 'SMS', 'WHATSAPP')"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["notify_attendees", "notification_channels"])
        nullable_fields = set(["notification_channels"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
