"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class RemovePermissionFromSpaceRoleAPIV1SpaceSpacesSpaceIDRolesRoleIDPermissionsPermissionIDDeleteRequestTypedDict(
    TypedDict
):
    space_id: int
    role_id: str
    permission_id: str


class RemovePermissionFromSpaceRoleAPIV1SpaceSpacesSpaceIDRolesRoleIDPermissionsPermissionIDDeleteRequest(
    BaseModel
):
    space_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    permission_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
