"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .spaceinheritancesettings import (
    SpaceInheritanceSettings,
    SpaceInheritanceSettingsTypedDict,
)
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SpaceWithRelationshipsResponseTypedDict(TypedDict):
    r"""Extended space response with relationship fields"""

    id: int
    title: str
    description: str
    timezone: str
    visibility: Nullable[int]
    creator_id: Nullable[str]
    parent_id: Nullable[int]
    children: NotRequired[List[int]]
    inheritance_settings: NotRequired[Nullable[SpaceInheritanceSettingsTypedDict]]


class SpaceWithRelationshipsResponse(BaseModel):
    r"""Extended space response with relationship fields"""

    id: int

    title: str

    description: str

    timezone: str

    visibility: Nullable[int]

    creator_id: Nullable[str]

    parent_id: Nullable[int]

    children: Optional[List[int]] = None

    inheritance_settings: OptionalNullable[SpaceInheritanceSettings] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["children", "inheritance_settings"])
        nullable_fields = set(
            ["visibility", "creator_id", "parent_id", "inheritance_settings"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
