"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .spacecontactinfo import SpaceContactInfo, SpaceContactInfoTypedDict
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class SpaceContactReadTypedDict(TypedDict):
    r"""Pydantic model for reading space contact data."""

    id: int
    r"""Space contact relationship ID"""
    space_id: int
    r"""Space ID"""
    contact_id: str
    r"""Contact ID"""
    created_at: str
    r"""Creation timestamp"""
    updated_at: str
    r"""Last update timestamp"""
    contact: NotRequired[Nullable[SpaceContactInfoTypedDict]]
    r"""Contact information"""


class SpaceContactRead(BaseModel):
    r"""Pydantic model for reading space contact data."""

    id: int
    r"""Space contact relationship ID"""

    space_id: int
    r"""Space ID"""

    contact_id: str
    r"""Contact ID"""

    created_at: str
    r"""Creation timestamp"""

    updated_at: str
    r"""Last update timestamp"""

    contact: OptionalNullable[SpaceContactInfo] = UNSET
    r"""Contact information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contact"])
        nullable_fields = set(["contact"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
