"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .togglefavoriterequest import ToggleFavoriteRequest, ToggleFavoriteRequestTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ToggleFavoriteAPIV1ContactsContactIDFavoritePatchRequestTypedDict(TypedDict):
    contact_id: str
    body: ToggleFavoriteRequestTypedDict


class ToggleFavoriteAPIV1ContactsContactIDFavoritePatchRequest(BaseModel):
    contact_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        ToggleFavoriteRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
