"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing_extensions import TypedDict


class TransferEventRequestTypedDict(TypedDict):
    target_org_id: str
    r"""UUID of the target organization to transfer this event to"""


class TransferEventRequest(BaseModel):
    target_org_id: str
    r"""UUID of the target organization to transfer this event to"""
