"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, HeaderMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class TriggerScheduledAutomationAPIV1AutomationAPIV1AutomationCronTriggerScheduledPostRequestTypedDict(
    TypedDict
):
    x_automation_key: str


class TriggerScheduledAutomationAPIV1AutomationAPIV1AutomationCronTriggerScheduledPostRequest(
    BaseModel
):
    x_automation_key: Annotated[
        str,
        pydantic.Field(alias="X-Automation-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
