"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, SecurityMetadata
from typing_extensions import Annotated, TypedDict


class UnlinkMilestoneAPIV1EventEventIDTimelineMilestoneEventIDDeleteSecurityTypedDict(
    TypedDict
):
    permission_dependency: str


class UnlinkMilestoneAPIV1EventEventIDTimelineMilestoneEventIDDeleteSecurity(BaseModel):
    permission_dependency: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ]


class UnlinkMilestoneAPIV1EventEventIDTimelineMilestoneEventIDDeleteRequestTypedDict(
    TypedDict
):
    event_id: int
    milestone_event_id: int


class UnlinkMilestoneAPIV1EventEventIDTimelineMilestoneEventIDDeleteRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    milestone_event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
