"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateplacerequest import UpdatePlaceRequest, UpdatePlaceRequestTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdatePlaceAPIV1PlacePlaceIDPutRequestTypedDict(TypedDict):
    place_id: int
    body: UpdatePlaceRequestTypedDict


class UpdatePlaceAPIV1PlacePlaceIDPutRequest(BaseModel):
    place_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        UpdatePlaceRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
