"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updaterolerequest import UpdateRoleRequest, UpdateRoleRequestTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateRoleEndpointAPIV1APIV1RolesRoleIDPutRequestTypedDict(TypedDict):
    role_id: str
    body: UpdateRoleRequestTypedDict


class UpdateRoleEndpointAPIV1APIV1RolesRoleIDPutRequest(BaseModel):
    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        UpdateRoleRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
