"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .spaceroleupdate import SpaceRoleUpdate, SpaceRoleUpdateTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateSpaceRoleAPIV1SpaceSpacesSpaceIDRolesRoleIDPutRequestTypedDict(TypedDict):
    space_id: int
    role_id: str
    body: SpaceRoleUpdateTypedDict


class UpdateSpaceRoleAPIV1SpaceSpacesSpaceIDRolesRoleIDPutRequest(BaseModel):
    space_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        SpaceRoleUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
