"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class UserProfileResponseTypedDict(TypedDict):
    id: str
    r"""User ID"""
    email: str
    r"""Email address"""
    created_at: datetime
    r"""Account creation date"""
    updated_at: datetime
    r"""Last update date"""
    external_auth_id: NotRequired[Nullable[str]]
    r"""External auth provider ID"""
    username: NotRequired[Nullable[str]]
    r"""Username"""
    avatar_url: NotRequired[Nullable[str]]
    r"""Avatar URL"""


class UserProfileResponse(BaseModel):
    id: str
    r"""User ID"""

    email: str
    r"""Email address"""

    created_at: datetime
    r"""Account creation date"""

    updated_at: datetime
    r"""Last update date"""

    external_auth_id: OptionalNullable[str] = UNSET
    r"""External auth provider ID"""

    username: OptionalNullable[str] = UNSET
    r"""Username"""

    avatar_url: OptionalNullable[str] = UNSET
    r"""Avatar URL"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["external_auth_id", "username", "avatar_url"])
        nullable_fields = set(["external_auth_id", "username", "avatar_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
