"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workflowexecutionresponse import (
    WorkflowExecutionResponse,
    WorkflowExecutionResponseTypedDict,
)
from openapi.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class WorkflowExecutionListResponseTypedDict(TypedDict):
    executions: List[WorkflowExecutionResponseTypedDict]
    r"""List of executions"""
    total: int
    r"""Total number of executions"""
    limit: int
    r"""Page size"""
    offset: int
    r"""Offset"""


class WorkflowExecutionListResponse(BaseModel):
    executions: List[WorkflowExecutionResponse]
    r"""List of executions"""

    total: int
    r"""Total number of executions"""

    limit: int
    r"""Page size"""

    offset: int
    r"""Offset"""
