"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from datetime import datetime
from linebundle_sdk import errors, models, utils
from linebundle_sdk._hooks import HookContext
from linebundle_sdk.types import OptionalNullable, UNSET
from linebundle_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Dict, Mapping, Optional


class AuditLogs(BaseSDK):
    def list_permissions(
        self,
        *,
        user_id: OptionalNullable[str] = UNSET,
        org_id: OptionalNullable[str] = UNSET,
        permission_code: OptionalNullable[str] = UNSET,
        result: OptionalNullable[str] = UNSET,
        start_date: OptionalNullable[datetime] = UNSET,
        end_date: OptionalNullable[datetime] = UNSET,
        skip: Optional[int] = 0,
        limit: Optional[int] = 100,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Dict[str, Any]:
        r"""List Permission Audit Logs

        List permission audit logs with filtering and pagination.

        Requires PERMISSION_READ permission.

        **Security**: Non-admin users can only view logs for their own organization.
        The org_id filter is automatically applied based on the user's permissions.

        **Query Parameters**:
        - user_id: Filter by specific user
        - org_id: Filter by organization (auto-scoped for non-admins)
        - permission_code: Filter by permission (e.g., \"SPACE_MANAGE_MEMBERS\")
        - result: Filter by result (\"granted\" or \"denied\")
        - start_date/end_date: Filter by date range
        - skip/limit: Pagination controls

        **Returns**: Paginated list of audit log entries with total count.

        :param user_id: Filter by user ID
        :param org_id: Filter by organization ID
        :param permission_code: Filter by permission code
        :param result: Filter by result (granted/denied)
        :param start_date: Filter by start date
        :param end_date: Filter by end date
        :param skip: Number of records to skip
        :param limit: Number of records to return
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListPermissionAuditLogsAPIV1AuditLogsPermissionsGetRequest(
            user_id=user_id,
            org_id=org_id,
            permission_code=permission_code,
            result=result,
            start_date=start_date,
            end_date=end_date,
            skip=skip,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/audit-logs/permissions",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_permission_audit_logs_api_v1_audit_logs_permissions_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            error_status_codes=["422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Dict[str, Any], http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.LinebundleDefaultError("Unexpected response received", http_res)

    async def list_permissions_async(
        self,
        *,
        user_id: OptionalNullable[str] = UNSET,
        org_id: OptionalNullable[str] = UNSET,
        permission_code: OptionalNullable[str] = UNSET,
        result: OptionalNullable[str] = UNSET,
        start_date: OptionalNullable[datetime] = UNSET,
        end_date: OptionalNullable[datetime] = UNSET,
        skip: Optional[int] = 0,
        limit: Optional[int] = 100,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Dict[str, Any]:
        r"""List Permission Audit Logs

        List permission audit logs with filtering and pagination.

        Requires PERMISSION_READ permission.

        **Security**: Non-admin users can only view logs for their own organization.
        The org_id filter is automatically applied based on the user's permissions.

        **Query Parameters**:
        - user_id: Filter by specific user
        - org_id: Filter by organization (auto-scoped for non-admins)
        - permission_code: Filter by permission (e.g., \"SPACE_MANAGE_MEMBERS\")
        - result: Filter by result (\"granted\" or \"denied\")
        - start_date/end_date: Filter by date range
        - skip/limit: Pagination controls

        **Returns**: Paginated list of audit log entries with total count.

        :param user_id: Filter by user ID
        :param org_id: Filter by organization ID
        :param permission_code: Filter by permission code
        :param result: Filter by result (granted/denied)
        :param start_date: Filter by start date
        :param end_date: Filter by end date
        :param skip: Number of records to skip
        :param limit: Number of records to return
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListPermissionAuditLogsAPIV1AuditLogsPermissionsGetRequest(
            user_id=user_id,
            org_id=org_id,
            permission_code=permission_code,
            result=result,
            start_date=start_date,
            end_date=end_date,
            skip=skip,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/audit-logs/permissions",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_permission_audit_logs_api_v1_audit_logs_permissions_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            error_status_codes=["422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Dict[str, Any], http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.LinebundleDefaultError("Unexpected response received", http_res)

    def get_permission_stats(
        self,
        *,
        org_id: OptionalNullable[str] = UNSET,
        start_date: OptionalNullable[datetime] = UNSET,
        end_date: OptionalNullable[datetime] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermissionAuditStats:
        r"""Get Permission Audit Stats

        Get aggregate statistics for permission audit logs.

        Requires PERMISSION_READ permission.

        **Security**: Non-admin users can only view stats for their own organization.

        **Returns**:
        - total_checks: Total number of permission checks
        - granted_count: Number of granted permissions
        - denied_count: Number of denied permissions
        - unique_users: Number of unique users who triggered checks
        - unique_permissions: Number of unique permissions checked
        - most_checked_permissions: Top 10 most frequently checked permissions
        - most_denied_permissions: Top 10 most frequently denied permissions

        :param org_id: Filter by organization ID
        :param start_date: Start date for statistics
        :param end_date: End date for statistics
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.GetPermissionAuditStatsAPIV1AuditLogsPermissionsStatsGetRequest(
                org_id=org_id,
                start_date=start_date,
                end_date=end_date,
            )
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/audit-logs/permissions/stats",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_permission_audit_stats_api_v1_audit_logs_permissions_stats_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            error_status_codes=["422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermissionAuditStats, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.LinebundleDefaultError("Unexpected response received", http_res)

    async def get_permission_stats_async(
        self,
        *,
        org_id: OptionalNullable[str] = UNSET,
        start_date: OptionalNullable[datetime] = UNSET,
        end_date: OptionalNullable[datetime] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermissionAuditStats:
        r"""Get Permission Audit Stats

        Get aggregate statistics for permission audit logs.

        Requires PERMISSION_READ permission.

        **Security**: Non-admin users can only view stats for their own organization.

        **Returns**:
        - total_checks: Total number of permission checks
        - granted_count: Number of granted permissions
        - denied_count: Number of denied permissions
        - unique_users: Number of unique users who triggered checks
        - unique_permissions: Number of unique permissions checked
        - most_checked_permissions: Top 10 most frequently checked permissions
        - most_denied_permissions: Top 10 most frequently denied permissions

        :param org_id: Filter by organization ID
        :param start_date: Start date for statistics
        :param end_date: End date for statistics
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.GetPermissionAuditStatsAPIV1AuditLogsPermissionsStatsGetRequest(
                org_id=org_id,
                start_date=start_date,
                end_date=end_date,
            )
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/audit-logs/permissions/stats",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_permission_audit_stats_api_v1_audit_logs_permissions_stats_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            error_status_codes=["422", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermissionAuditStats, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.LinebundleDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.LinebundleDefaultError("Unexpected response received", http_res)
