/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SpaceRole, SpaceRole$outboundSchema } from "./space-role.js";

/**
 * Request model for adding a member to a space
 */
export type AddSpaceMemberRequest = {
  /**
   * Email of the user to add
   */
  email: string;
  /**
   * Space roles with hierarchical permissions
   */
  role?: SpaceRole | undefined;
};

/** @internal */
export type AddSpaceMemberRequest$Outbound = {
  email: string;
  role?: string | undefined;
};

/** @internal */
export const AddSpaceMemberRequest$outboundSchema: z.ZodMiniType<
  AddSpaceMemberRequest$Outbound,
  AddSpaceMemberRequest
> = z.object({
  email: z.string(),
  role: z.optional(SpaceRole$outboundSchema),
});

export function addSpaceMemberRequestToJSON(
  addSpaceMemberRequest: AddSpaceMemberRequest,
): string {
  return JSON.stringify(
    AddSpaceMemberRequest$outboundSchema.parse(addSpaceMemberRequest),
  );
}
