/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AppUserAdapterInputApiV1ResponseMessageResponse = {
  /**
   * Success message
   */
  message: string;
};

/** @internal */
export const AppUserAdapterInputApiV1ResponseMessageResponse$inboundSchema:
  z.ZodMiniType<AppUserAdapterInputApiV1ResponseMessageResponse, unknown> = z
    .object({
      message: types.string(),
    });

export function appUserAdapterInputApiV1ResponseMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AppUserAdapterInputApiV1ResponseMessageResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppUserAdapterInputApiV1ResponseMessageResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppUserAdapterInputApiV1ResponseMessageResponse' from JSON`,
  );
}
