/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SenderProfile,
  SenderProfile$inboundSchema,
} from "./sender-profile.js";

export type AppChatAdapterInputSchemasMessageMessageResponse = {
  id: string;
  roomId: string;
  senderId: string | null;
  /**
   * Sender profile information
   */
  sender?: SenderProfile | null | undefined;
  messageType: string;
  content: string;
  metadata: { [k: string]: any };
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const AppChatAdapterInputSchemasMessageMessageResponse$inboundSchema:
  z.ZodMiniType<AppChatAdapterInputSchemasMessageMessageResponse, unknown> = z
    .pipe(
      z.object({
        id: types.string(),
        room_id: types.string(),
        sender_id: types.nullable(types.string()),
        sender: z.optional(z.nullable(SenderProfile$inboundSchema)),
        message_type: types.string(),
        content: types.string(),
        metadata_: z.record(z.string(), z.any()),
        created_at: types.date(),
        updated_at: types.date(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "room_id": "roomId",
          "sender_id": "senderId",
          "message_type": "messageType",
          "metadata_": "metadata",
          "created_at": "createdAt",
          "updated_at": "updatedAt",
        });
      }),
    );

export function appChatAdapterInputSchemasMessageMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AppChatAdapterInputSchemasMessageMessageResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppChatAdapterInputSchemasMessageMessageResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppChatAdapterInputSchemasMessageMessageResponse' from JSON`,
  );
}
