/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Basic info about a base event when the current event is a milestone.
 */
export type BaseEventInfo = {
  /**
   * Base event ID
   */
  id: number;
  /**
   * Base event title
   */
  title: string;
  /**
   * Base event description
   */
  description?: string | null | undefined;
  /**
   * Base event start datetime (ISO format)
   */
  startDt: string;
  /**
   * Base event end datetime (ISO format)
   */
  endDt: string;
  /**
   * Base event timezone
   */
  timezone: string;
};

/** @internal */
export const BaseEventInfo$inboundSchema: z.ZodMiniType<
  BaseEventInfo,
  unknown
> = z.pipe(
  z.object({
    id: types.number(),
    title: types.string(),
    description: z.optional(z.nullable(types.string())),
    start_dt: types.string(),
    end_dt: types.string(),
    timezone: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_dt": "startDt",
      "end_dt": "endDt",
    });
  }),
);

export function baseEventInfoFromJSON(
  jsonString: string,
): SafeParseResult<BaseEventInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseEventInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseEventInfo' from JSON`,
  );
}
