/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { blobLikeSchema } from "../types/blobs.js";

export type BodyCreateEventApiV1EventPostFile = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyCreateEventApiV1EventPost = {
  /**
   * JSON string of CreateEventRequest
   */
  request: string;
  /**
   * Optional cover image file
   */
  file?: BodyCreateEventApiV1EventPostFile | Blob | undefined;
};

/** @internal */
export type BodyCreateEventApiV1EventPostFile$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const BodyCreateEventApiV1EventPostFile$outboundSchema: z.ZodMiniType<
  BodyCreateEventApiV1EventPostFile$Outbound,
  BodyCreateEventApiV1EventPostFile
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function bodyCreateEventApiV1EventPostFileToJSON(
  bodyCreateEventApiV1EventPostFile: BodyCreateEventApiV1EventPostFile,
): string {
  return JSON.stringify(
    BodyCreateEventApiV1EventPostFile$outboundSchema.parse(
      bodyCreateEventApiV1EventPostFile,
    ),
  );
}

/** @internal */
export type BodyCreateEventApiV1EventPost$Outbound = {
  request: string;
  file?: BodyCreateEventApiV1EventPostFile$Outbound | Blob | undefined;
};

/** @internal */
export const BodyCreateEventApiV1EventPost$outboundSchema: z.ZodMiniType<
  BodyCreateEventApiV1EventPost$Outbound,
  BodyCreateEventApiV1EventPost
> = z.object({
  request: z.string(),
  file: z.optional(
    z.union([
      z.lazy(() => BodyCreateEventApiV1EventPostFile$outboundSchema),
      blobLikeSchema,
    ]),
  ),
});

export function bodyCreateEventApiV1EventPostToJSON(
  bodyCreateEventApiV1EventPost: BodyCreateEventApiV1EventPost,
): string {
  return JSON.stringify(
    BodyCreateEventApiV1EventPost$outboundSchema.parse(
      bodyCreateEventApiV1EventPost,
    ),
  );
}
