/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Response schema for booking data
 */
export type BookingRead = {
  /**
   * Booking ID
   */
  id: number;
  /**
   * Place ID
   */
  placeId: number;
  /**
   * User ID
   */
  userId: string;
  /**
   * Booking title
   */
  title: string;
  /**
   * Booking description
   */
  description?: string | null | undefined;
  /**
   * Start datetime
   */
  startDt: string;
  /**
   * End datetime
   */
  endDt: string;
  /**
   * Booking status
   */
  status: string;
  /**
   * Created datetime
   */
  createdAt: string;
  /**
   * Updated datetime
   */
  updatedAt: string;
};

/** @internal */
export const BookingRead$inboundSchema: z.ZodMiniType<BookingRead, unknown> = z
  .pipe(
    z.object({
      id: types.number(),
      place_id: types.number(),
      user_id: types.string(),
      title: types.string(),
      description: z.optional(z.nullable(types.string())),
      start_dt: types.string(),
      end_dt: types.string(),
      status: types.string(),
      created_at: types.string(),
      updated_at: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "place_id": "placeId",
        "user_id": "userId",
        "start_dt": "startDt",
        "end_dt": "endDt",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
      });
    }),
  );

export function bookingReadFromJSON(
  jsonString: string,
): SafeParseResult<BookingRead, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BookingRead$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BookingRead' from JSON`,
  );
}
