/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TaskMetadata, TaskMetadata$inboundSchema } from "./task-metadata.js";

/**
 * Combined response with all metadata types.
 */
export type CombinedMetadataResponse = {
  triggers: Array<TaskMetadata>;
  conditions: Array<TaskMetadata>;
  actions: Array<TaskMetadata>;
};

/** @internal */
export const CombinedMetadataResponse$inboundSchema: z.ZodMiniType<
  CombinedMetadataResponse,
  unknown
> = z.object({
  triggers: z.array(TaskMetadata$inboundSchema),
  conditions: z.array(TaskMetadata$inboundSchema),
  actions: z.array(TaskMetadata$inboundSchema),
});

export function combinedMetadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<CombinedMetadataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CombinedMetadataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CombinedMetadataResponse' from JSON`,
  );
}
