/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateOnlineMeetingRequest = {
  /**
   * Place title
   */
  title: string;
  /**
   * Place description
   */
  description: string;
  /**
   * Visibility level
   */
  visibility: number;
  /**
   * Keywords
   */
  keywords?: Array<string> | undefined;
  /**
   * Place type
   */
  placeType: "online_meeting";
  /**
   * Meeting URL
   */
  meetingUrl: string;
};

/** @internal */
export type CreateOnlineMeetingRequest$Outbound = {
  title: string;
  description: string;
  visibility: number;
  keywords?: Array<string> | undefined;
  place_type: "online_meeting";
  meeting_url: string;
};

/** @internal */
export const CreateOnlineMeetingRequest$outboundSchema: z.ZodMiniType<
  CreateOnlineMeetingRequest$Outbound,
  CreateOnlineMeetingRequest
> = z.pipe(
  z.object({
    title: z.string(),
    description: z.string(),
    visibility: z.int(),
    keywords: z.optional(z.array(z.string())),
    placeType: z.literal("online_meeting"),
    meetingUrl: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      placeType: "place_type",
      meetingUrl: "meeting_url",
    });
  }),
);

export function createOnlineMeetingRequestToJSON(
  createOnlineMeetingRequest: CreateOnlineMeetingRequest,
): string {
  return JSON.stringify(
    CreateOnlineMeetingRequest$outboundSchema.parse(createOnlineMeetingRequest),
  );
}
