/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { AgentType, AgentType$outboundSchema } from "./agent-type.js";

export type CreateSessionRequest = {
  /**
   * Enum representing different types of AI agents.
   */
  agentType?: AgentType | undefined;
  /**
   * Human-readable session title (auto-generated if not provided)
   */
  title?: string | null | undefined;
  /**
   * OpenAI model to use (e.g., gpt-4o, gpt-4o-mini)
   */
  model?: string | undefined;
  /**
   * LLM temperature for response randomness (0.0-2.0)
   */
  temperature?: number | undefined;
  /**
   * Custom system prompt to override default agent behavior
   */
  systemPrompt?: string | null | undefined;
};

/** @internal */
export type CreateSessionRequest$Outbound = {
  agent_type?: string | undefined;
  title?: string | null | undefined;
  model: string;
  temperature: number;
  system_prompt?: string | null | undefined;
};

/** @internal */
export const CreateSessionRequest$outboundSchema: z.ZodMiniType<
  CreateSessionRequest$Outbound,
  CreateSessionRequest
> = z.pipe(
  z.object({
    agentType: z.optional(AgentType$outboundSchema),
    title: z.optional(z.nullable(z.string())),
    model: z._default(z.string(), "gpt-4o"),
    temperature: z._default(z.number(), 0.7),
    systemPrompt: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      agentType: "agent_type",
      systemPrompt: "system_prompt",
    });
  }),
);

export function createSessionRequestToJSON(
  createSessionRequest: CreateSessionRequest,
): string {
  return JSON.stringify(
    CreateSessionRequest$outboundSchema.parse(createSessionRequest),
  );
}
