/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateEventRequest = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null | undefined;
  /**
   * Start date
   */
  startDt: string;
  /**
   * Start time
   */
  startTm: string;
  /**
   * End date
   */
  endDt: string;
  /**
   * End time
   */
  endTm: string;
  /**
   * Timezone (must be a valid IANA timezone, e.g., 'UTC', 'America/New_York', 'Europe/London')
   */
  timezone: string;
  /**
   * Visibility (optional - defaults to PRIVATE if no spaces, inherits from spaces if spaces provided)
   */
  visibility?: number | null | undefined;
  /**
   * Keywords
   */
  keywords?: Array<string> | null | undefined;
  /**
   * Space IDs
   */
  spaceIds?: Array<number> | null | undefined;
  /**
   * Document IDs (UUIDs from document service)
   */
  documentIds?: Array<string> | null | undefined;
  /**
   * Repeat Days
   */
  repeatDays?: Array<number> | null | undefined;
  /**
   * Repeat Presets
   */
  repeatPresets?: string | null | undefined;
  /**
   * Timeline Preset
   */
  timelinePreset?: string | null | undefined;
  /**
   * Latitude coordinate (-90 to 90)
   */
  latitude?: number | null | undefined;
  /**
   * Longitude coordinate (-180 to 180)
   */
  longitude?: number | null | undefined;
  /**
   * Physical address
   */
  address?: string | null | undefined;
  /**
   * Event Metadata (JSON)
   */
  eventMetadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type CreateEventRequest$Outbound = {
  title: string;
  description?: string | null | undefined;
  start_dt: string;
  start_tm: string;
  end_dt: string;
  end_tm: string;
  timezone: string;
  visibility?: number | null | undefined;
  keywords?: Array<string> | null | undefined;
  space_ids?: Array<number> | null | undefined;
  document_ids?: Array<string> | null | undefined;
  repeat_days?: Array<number> | null | undefined;
  repeat_presets?: string | null | undefined;
  timeline_preset?: string | null | undefined;
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  address?: string | null | undefined;
  event_metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const CreateEventRequest$outboundSchema: z.ZodMiniType<
  CreateEventRequest$Outbound,
  CreateEventRequest
> = z.pipe(
  z.object({
    title: z.string(),
    description: z.optional(z.nullable(z.string())),
    startDt: z.string(),
    startTm: z.string(),
    endDt: z.string(),
    endTm: z.string(),
    timezone: z.string(),
    visibility: z.optional(z.nullable(z.int())),
    keywords: z.optional(z.nullable(z.array(z.string()))),
    spaceIds: z.optional(z.nullable(z.array(z.int()))),
    documentIds: z.optional(z.nullable(z.array(z.string()))),
    repeatDays: z.optional(z.nullable(z.array(z.int()))),
    repeatPresets: z.optional(z.nullable(z.string())),
    timelinePreset: z.optional(z.nullable(z.string())),
    latitude: z.optional(z.nullable(z.number())),
    longitude: z.optional(z.nullable(z.number())),
    address: z.optional(z.nullable(z.string())),
    eventMetadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      startDt: "start_dt",
      startTm: "start_tm",
      endDt: "end_dt",
      endTm: "end_tm",
      spaceIds: "space_ids",
      documentIds: "document_ids",
      repeatDays: "repeat_days",
      repeatPresets: "repeat_presets",
      timelinePreset: "timeline_preset",
      eventMetadata: "event_metadata",
    });
  }),
);

export function createEventRequestToJSON(
  createEventRequest: CreateEventRequest,
): string {
  return JSON.stringify(
    CreateEventRequest$outboundSchema.parse(createEventRequest),
  );
}
