/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Request model for creating a new contact.
 */
export type CreateContactRequest = {
  /**
   * Organization ID
   */
  orgId?: string | null | undefined;
  /**
   * First name
   */
  firstName?: string | null | undefined;
  /**
   * Last name
   */
  lastName?: string | null | undefined;
  /**
   * Middle name
   */
  middleName?: string | null | undefined;
  /**
   * Nickname
   */
  nickname?: string | null | undefined;
  /**
   * Email address
   */
  email?: string | null | undefined;
  /**
   * Primary phone number
   */
  phonePrimary?: string | null | undefined;
  /**
   * Secondary phone number
   */
  phoneSecondary?: string | null | undefined;
  /**
   * Work phone number
   */
  phoneWork?: string | null | undefined;
  /**
   * Address line 1
   */
  addressLine1?: string | null | undefined;
  /**
   * Address line 2
   */
  addressLine2?: string | null | undefined;
  /**
   * City
   */
  city?: string | null | undefined;
  /**
   * State or province
   */
  stateProvince?: string | null | undefined;
  /**
   * Postal code
   */
  postalCode?: string | null | undefined;
  /**
   * Country
   */
  country?: string | null | undefined;
  /**
   * Company name
   */
  company?: string | null | undefined;
  /**
   * Job title
   */
  jobTitle?: string | null | undefined;
  /**
   * Website URL
   */
  website?: string | null | undefined;
  /**
   * Additional notes
   */
  notes?: string | null | undefined;
  /**
   * Avatar URL
   */
  avatarUrl?: string | null | undefined;
  /**
   * Linked user ID
   */
  linkedUserId?: string | null | undefined;
  /**
   * Whether contact is marked as favorite
   */
  isFavorite?: boolean | undefined;
  /**
   * Tags for categorization
   */
  tags?: Array<string> | null | undefined;
};

/** @internal */
export type CreateContactRequest$Outbound = {
  org_id?: string | null | undefined;
  first_name?: string | null | undefined;
  last_name?: string | null | undefined;
  middle_name?: string | null | undefined;
  nickname?: string | null | undefined;
  email?: string | null | undefined;
  phone_primary?: string | null | undefined;
  phone_secondary?: string | null | undefined;
  phone_work?: string | null | undefined;
  address_line1?: string | null | undefined;
  address_line2?: string | null | undefined;
  city?: string | null | undefined;
  state_province?: string | null | undefined;
  postal_code?: string | null | undefined;
  country?: string | null | undefined;
  company?: string | null | undefined;
  job_title?: string | null | undefined;
  website?: string | null | undefined;
  notes?: string | null | undefined;
  avatar_url?: string | null | undefined;
  linked_user_id?: string | null | undefined;
  is_favorite: boolean;
  tags?: Array<string> | null | undefined;
};

/** @internal */
export const CreateContactRequest$outboundSchema: z.ZodMiniType<
  CreateContactRequest$Outbound,
  CreateContactRequest
> = z.pipe(
  z.object({
    orgId: z.optional(z.nullable(z.string())),
    firstName: z.optional(z.nullable(z.string())),
    lastName: z.optional(z.nullable(z.string())),
    middleName: z.optional(z.nullable(z.string())),
    nickname: z.optional(z.nullable(z.string())),
    email: z.optional(z.nullable(z.string())),
    phonePrimary: z.optional(z.nullable(z.string())),
    phoneSecondary: z.optional(z.nullable(z.string())),
    phoneWork: z.optional(z.nullable(z.string())),
    addressLine1: z.optional(z.nullable(z.string())),
    addressLine2: z.optional(z.nullable(z.string())),
    city: z.optional(z.nullable(z.string())),
    stateProvince: z.optional(z.nullable(z.string())),
    postalCode: z.optional(z.nullable(z.string())),
    country: z.optional(z.nullable(z.string())),
    company: z.optional(z.nullable(z.string())),
    jobTitle: z.optional(z.nullable(z.string())),
    website: z.optional(z.nullable(z.string())),
    notes: z.optional(z.nullable(z.string())),
    avatarUrl: z.optional(z.nullable(z.string())),
    linkedUserId: z.optional(z.nullable(z.string())),
    isFavorite: z._default(z.boolean(), false),
    tags: z.optional(z.nullable(z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      orgId: "org_id",
      firstName: "first_name",
      lastName: "last_name",
      middleName: "middle_name",
      phonePrimary: "phone_primary",
      phoneSecondary: "phone_secondary",
      phoneWork: "phone_work",
      addressLine1: "address_line1",
      addressLine2: "address_line2",
      stateProvince: "state_province",
      postalCode: "postal_code",
      jobTitle: "job_title",
      avatarUrl: "avatar_url",
      linkedUserId: "linked_user_id",
      isFavorite: "is_favorite",
    });
  }),
);

export function createContactRequestToJSON(
  createContactRequest: CreateContactRequest,
): string {
  return JSON.stringify(
    CreateContactRequest$outboundSchema.parse(createContactRequest),
  );
}
