/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateDirectRoomRequest = {
  /**
   * User ID to create direct message with
   */
  otherUserId: string;
};

/** @internal */
export type CreateDirectRoomRequest$Outbound = {
  other_user_id: string;
};

/** @internal */
export const CreateDirectRoomRequest$outboundSchema: z.ZodMiniType<
  CreateDirectRoomRequest$Outbound,
  CreateDirectRoomRequest
> = z.pipe(
  z.object({
    otherUserId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      otherUserId: "other_user_id",
    });
  }),
);

export function createDirectRoomRequestToJSON(
  createDirectRoomRequest: CreateDirectRoomRequest,
): string {
  return JSON.stringify(
    CreateDirectRoomRequest$outboundSchema.parse(createDirectRoomRequest),
  );
}
