/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AppEventDomainEntityEventSpaceInfo,
  AppEventDomainEntityEventSpaceInfo$inboundSchema,
} from "./app-event-domain-entity-event-space-info.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { EventRead, EventRead$inboundSchema } from "./event-read.js";

/**
 * Published event version response.
 */
export type EventVersionRead = {
  id: number;
  eventId: number;
  transactionId: number;
  status: string;
  title: string;
  description?: string | null | undefined;
  startDt: Date;
  endDt: Date;
  /**
   * Timezone (IANA timezone format, e.g., 'UTC', 'America/New_York', 'Europe/London')
   */
  timezone: string;
  visibility: number | null;
  keywords: Array<string>;
  latitude: number | null;
  longitude: number | null;
  address?: string | null | undefined;
  eventMetadata?: { [k: string]: any } | null | undefined;
  publishedAt: Date;
  publishedBy: string;
  spaces?: Array<AppEventDomainEntityEventSpaceInfo> | undefined;
  documents?: Array<string> | undefined;
  timeline?: Array<EventRead> | undefined;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const EventVersionRead$inboundSchema: z.ZodMiniType<
  EventVersionRead,
  unknown
> = z.pipe(
  z.object({
    id: types.number(),
    event_id: types.number(),
    transaction_id: types.number(),
    status: types.string(),
    title: types.string(),
    description: z.optional(z.nullable(types.string())),
    start_dt: types.date(),
    end_dt: types.date(),
    timezone: types.string(),
    visibility: types.nullable(types.number()),
    keywords: z.array(types.string()),
    latitude: types.nullable(types.number()),
    longitude: types.nullable(types.number()),
    address: z.optional(z.nullable(types.string())),
    event_metadata: z.optional(z.nullable(z.record(z.string(), z.any()))),
    published_at: types.date(),
    published_by: types.string(),
    spaces: types.optional(
      z.array(AppEventDomainEntityEventSpaceInfo$inboundSchema),
    ),
    documents: types.optional(z.array(types.string())),
    timeline: types.optional(z.array(EventRead$inboundSchema)),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_id": "eventId",
      "transaction_id": "transactionId",
      "start_dt": "startDt",
      "end_dt": "endDt",
      "event_metadata": "eventMetadata",
      "published_at": "publishedAt",
      "published_by": "publishedBy",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function eventVersionReadFromJSON(
  jsonString: string,
): SafeParseResult<EventVersionRead, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventVersionRead$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventVersionRead' from JSON`,
  );
}
