/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  EventAdvancedFilters,
  EventAdvancedFilters$Outbound,
  EventAdvancedFilters$outboundSchema,
} from "./event-advanced-filters.js";
import {
  EventPaginationOptions,
  EventPaginationOptions$Outbound,
  EventPaginationOptions$outboundSchema,
} from "./event-pagination-options.js";
import {
  EventSortOptions,
  EventSortOptions$Outbound,
  EventSortOptions$outboundSchema,
} from "./event-sort-options.js";

/**
 * Complete filter request for POST endpoint.
 */
export type EventFilterRequest = {
  /**
   * Advanced filters
   */
  filters?: EventAdvancedFilters | null | undefined;
  /**
   * Sort options
   */
  sort?: EventSortOptions | null | undefined;
  /**
   * Pagination options
   */
  pagination?: EventPaginationOptions | null | undefined;
};

/** @internal */
export type EventFilterRequest$Outbound = {
  filters?: EventAdvancedFilters$Outbound | null | undefined;
  sort?: EventSortOptions$Outbound | null | undefined;
  pagination?: EventPaginationOptions$Outbound | null | undefined;
};

/** @internal */
export const EventFilterRequest$outboundSchema: z.ZodMiniType<
  EventFilterRequest$Outbound,
  EventFilterRequest
> = z.object({
  filters: z.optional(z.nullable(EventAdvancedFilters$outboundSchema)),
  sort: z.optional(z.nullable(EventSortOptions$outboundSchema)),
  pagination: z.optional(z.nullable(EventPaginationOptions$outboundSchema)),
});

export function eventFilterRequestToJSON(
  eventFilterRequest: EventFilterRequest,
): string {
  return JSON.stringify(
    EventFilterRequest$outboundSchema.parse(eventFilterRequest),
  );
}
