/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AttendeeInfo, AttendeeInfo$inboundSchema } from "./attendee-info.js";
import {
  AttendeeStatus,
  AttendeeStatus$inboundSchema,
} from "./attendee-status.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Pydantic model for reading event attendee data.
 */
export type EventAttendeeRead = {
  /**
   * Attendee status enumeration.
   */
  status?: AttendeeStatus | undefined;
  /**
   * Additional notes
   */
  notes?: string | null | undefined;
  /**
   * Attendee relationship ID
   */
  id: number;
  /**
   * Event ID
   */
  eventId: number;
  /**
   * Contact ID
   */
  contactId: string;
  /**
   * Whether attendee has checked in
   */
  isCheckedIn: boolean;
  /**
   * Check-in timestamp
   */
  checkedInAt?: Date | null | undefined;
  /**
   * Invitation timestamp
   */
  invitedAt?: Date | null | undefined;
  /**
   * Response timestamp
   */
  respondedAt?: Date | null | undefined;
  /**
   * Creation timestamp
   */
  createdAt: Date;
  /**
   * Last update timestamp
   */
  updatedAt: Date;
  /**
   * Contact information
   */
  contact?: AttendeeInfo | null | undefined;
};

/** @internal */
export const EventAttendeeRead$inboundSchema: z.ZodMiniType<
  EventAttendeeRead,
  unknown
> = z.pipe(
  z.object({
    status: types.optional(AttendeeStatus$inboundSchema),
    notes: z.optional(z.nullable(types.string())),
    id: types.number(),
    event_id: types.number(),
    contact_id: types.string(),
    is_checked_in: types.boolean(),
    checked_in_at: z.optional(z.nullable(types.date())),
    invited_at: z.optional(z.nullable(types.date())),
    responded_at: z.optional(z.nullable(types.date())),
    created_at: types.date(),
    updated_at: types.date(),
    contact: z.optional(z.nullable(AttendeeInfo$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_id": "eventId",
      "contact_id": "contactId",
      "is_checked_in": "isCheckedIn",
      "checked_in_at": "checkedInAt",
      "invited_at": "invitedAt",
      "responded_at": "respondedAt",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function eventAttendeeReadFromJSON(
  jsonString: string,
): SafeParseResult<EventAttendeeRead, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventAttendeeRead$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventAttendeeRead' from JSON`,
  );
}
