/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Pagination options for event queries.
 */
export type EventPaginationOptions = {
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Offset for pagination
   */
  offset?: number | undefined;
};

/** @internal */
export type EventPaginationOptions$Outbound = {
  limit: number;
  offset: number;
};

/** @internal */
export const EventPaginationOptions$outboundSchema: z.ZodMiniType<
  EventPaginationOptions$Outbound,
  EventPaginationOptions
> = z.object({
  limit: z._default(z.int(), 10),
  offset: z._default(z.int(), 0),
});

export function eventPaginationOptionsToJSON(
  eventPaginationOptions: EventPaginationOptions,
): string {
  return JSON.stringify(
    EventPaginationOptions$outboundSchema.parse(eventPaginationOptions),
  );
}
