/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GetSpaceListResponseDTO = {
  /**
   * ID
   */
  id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Created At
   */
  createdAt: string;
  /**
   * Updated At
   */
  updatedAt: string;
  /**
   * Timezone
   */
  timezone: string;
  /**
   * Visibility
   */
  visibility?: number | null | undefined;
  /**
   * Creator ID
   */
  creatorId?: string | null | undefined;
  /**
   * Organization ID
   */
  orgId?: string | null | undefined;
  parentId?: number | null | undefined;
  children?: Array<number> | undefined;
  inheritanceSettings?: { [k: string]: any } | null | undefined;
  /**
   * Number of members in the space
   */
  memberCount: number;
  /**
   * Number of events in the space
   */
  eventCount: number;
  /**
   * Whether the current user is a member of this space
   */
  isMember: boolean;
  /**
   * Current user's role in the space
   */
  userRole?: string | null | undefined;
};

/** @internal */
export const GetSpaceListResponseDTO$inboundSchema: z.ZodMiniType<
  GetSpaceListResponseDTO,
  unknown
> = z.pipe(
  z.object({
    id: types.number(),
    title: types.string(),
    description: types.string(),
    created_at: types.string(),
    updated_at: types.string(),
    timezone: types.string(),
    visibility: z.optional(z.nullable(types.number())),
    creator_id: z.optional(z.nullable(types.string())),
    org_id: z.optional(z.nullable(types.string())),
    parent_id: z.optional(z.nullable(types.number())),
    children: types.optional(z.array(types.number())),
    inheritance_settings: z.optional(z.nullable(z.record(z.string(), z.any()))),
    member_count: z._default(types.number(), 0),
    event_count: z._default(types.number(), 0),
    is_member: z._default(types.boolean(), false),
    user_role: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "creator_id": "creatorId",
      "org_id": "orgId",
      "parent_id": "parentId",
      "inheritance_settings": "inheritanceSettings",
      "member_count": "memberCount",
      "event_count": "eventCount",
      "is_member": "isMember",
      "user_role": "userRole",
    });
  }),
);

export function getSpaceListResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<GetSpaceListResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSpaceListResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSpaceListResponseDTO' from JSON`,
  );
}
