/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LocationUpdateSchema = {
  /**
   * Latitude coordinate
   */
  latitude?: number | null | undefined;
  /**
   * Longitude coordinate
   */
  longitude?: number | null | undefined;
  /**
   * Physical address
   */
  address?: string | null | undefined;
};

/** @internal */
export type LocationUpdateSchema$Outbound = {
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  address?: string | null | undefined;
};

/** @internal */
export const LocationUpdateSchema$outboundSchema: z.ZodMiniType<
  LocationUpdateSchema$Outbound,
  LocationUpdateSchema
> = z.object({
  latitude: z.optional(z.nullable(z.number())),
  longitude: z.optional(z.nullable(z.number())),
  address: z.optional(z.nullable(z.string())),
});

export function locationUpdateSchemaToJSON(
  locationUpdateSchema: LocationUpdateSchema,
): string {
  return JSON.stringify(
    LocationUpdateSchema$outboundSchema.parse(locationUpdateSchema),
  );
}
