/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OrgCostSummary,
  OrgCostSummary$inboundSchema,
} from "./org-cost-summary.js";
import {
  UserCostBreakdown,
  UserCostBreakdown$inboundSchema,
} from "./user-cost-breakdown.js";

export type OrgCostDetailResponse = {
  summary: OrgCostSummary;
  /**
   * Cost breakdown by user
   */
  byUser: Array<UserCostBreakdown>;
};

/** @internal */
export const OrgCostDetailResponse$inboundSchema: z.ZodMiniType<
  OrgCostDetailResponse,
  unknown
> = z.pipe(
  z.object({
    summary: OrgCostSummary$inboundSchema,
    by_user: z.array(UserCostBreakdown$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "by_user": "byUser",
    });
  }),
);

export function orgCostDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrgCostDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrgCostDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrgCostDetailResponse' from JSON`,
  );
}
