/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type OrganizationResponse = {
  id: string;
  plan: string;
  allowPublicVisibility: boolean;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const OrganizationResponse$inboundSchema: z.ZodMiniType<
  OrganizationResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    plan: types.string(),
    allow_public_visibility: types.boolean(),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "allow_public_visibility": "allowPublicVisibility",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function organizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationResponse' from JSON`,
  );
}
