/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type PublishEventWithNotificationsRequest = {
  /**
   * Whether to notify attendees about the publication
   */
  notifyAttendees?: boolean | undefined;
  /**
   * List of channels to use for notification (e.g., 'EMAIL', 'SMS', 'WHATSAPP')
   */
  notificationChannels?: Array<string> | null | undefined;
};

/** @internal */
export type PublishEventWithNotificationsRequest$Outbound = {
  notify_attendees: boolean;
  notification_channels?: Array<string> | null | undefined;
};

/** @internal */
export const PublishEventWithNotificationsRequest$outboundSchema: z.ZodMiniType<
  PublishEventWithNotificationsRequest$Outbound,
  PublishEventWithNotificationsRequest
> = z.pipe(
  z.object({
    notifyAttendees: z._default(z.boolean(), false),
    notificationChannels: z.optional(z.nullable(z.array(z.string()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      notifyAttendees: "notify_attendees",
      notificationChannels: "notification_channels",
    });
  }),
);

export function publishEventWithNotificationsRequestToJSON(
  publishEventWithNotificationsRequest: PublishEventWithNotificationsRequest,
): string {
  return JSON.stringify(
    PublishEventWithNotificationsRequest$outboundSchema.parse(
      publishEventWithNotificationsRequest,
    ),
  );
}
