/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PermissionResponse,
  PermissionResponse$inboundSchema,
} from "./permission-response.js";

export type RoleResponse = {
  /**
   * Role ID
   */
  id: string;
  /**
   * Organization ID
   */
  orgId: string;
  /**
   * Role name
   */
  name: string;
  /**
   * Role description
   */
  description?: string | null | undefined;
  /**
   * List of permissions
   */
  permissions?: Array<PermissionResponse> | undefined;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const RoleResponse$inboundSchema: z.ZodMiniType<RoleResponse, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      org_id: types.string(),
      name: types.string(),
      description: z.optional(z.nullable(types.string())),
      permissions: types.optional(z.array(PermissionResponse$inboundSchema)),
      created_at: types.date(),
      updated_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "org_id": "orgId",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
      });
    }),
  );

export function roleResponseFromJSON(
  jsonString: string,
): SafeParseResult<RoleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoleResponse' from JSON`,
  );
}
