/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { RoomType, RoomType$inboundSchema } from "./room-type.js";

export type RoomResponse = {
  id: string;
  orgId?: string | null | undefined;
  roomType: RoomType;
  name: string | null;
  description: string | null;
  visibility: number;
  /**
   * Named schema for arbitrary key-value metadata on chat rooms and messages.
   *
   * @remarks
   *
   * Using ``RootModel`` instead of an inline ``dict[str, Any]`` ensures FastAPI/Pydantic
   * emits a single named ``ChatMetadata`` component (``$ref``) in the OpenAPI spec,
   * preventing Speakeasy from flagging duplicate anonymous schemas.
   */
  metadata?: { [k: string]: any } | undefined;
  creatorId: string;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const RoomResponse$inboundSchema: z.ZodMiniType<RoomResponse, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      org_id: z.optional(z.nullable(types.string())),
      room_type: RoomType$inboundSchema,
      name: types.nullable(types.string()),
      description: types.nullable(types.string()),
      visibility: types.number(),
      metadata_: types.optional(z.record(z.string(), z.any())),
      creator_id: types.string(),
      created_at: types.date(),
      updated_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "org_id": "orgId",
        "room_type": "roomType",
        "metadata_": "metadata",
        "creator_id": "creatorId",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
      });
    }),
  );

export function roomResponseFromJSON(
  jsonString: string,
): SafeParseResult<RoomResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoomResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoomResponse' from JSON`,
  );
}
