/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Automation rule response.
 */
export type RuleResponse = {
  id: string;
  orgId: string | null;
  creatorId: string;
  name: string;
  description: string | null;
  scope: string;
  scopeId: string | null;
  enabled: boolean;
  priority: number;
  conditions: { [k: string]: any };
  actions: Array<{ [k: string]: any }>;
  schedule: { [k: string]: any };
  constraints: { [k: string]: any } | null;
  ruleMetadata: { [k: string]: any } | null;
  version: number;
  createdAt: Date;
  updatedAt: Date;
  scopeMode?: string | null | undefined;
};

/** @internal */
export const RuleResponse$inboundSchema: z.ZodMiniType<RuleResponse, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      org_id: types.nullable(types.string()),
      creator_id: types.string(),
      name: types.string(),
      description: types.nullable(types.string()),
      scope: types.string(),
      scope_id: types.nullable(types.string()),
      enabled: types.boolean(),
      priority: types.number(),
      conditions: z.record(z.string(), z.any()),
      actions: z.array(z.record(z.string(), z.any())),
      schedule: z.record(z.string(), z.any()),
      constraints: types.nullable(z.record(z.string(), z.any())),
      rule_metadata: types.nullable(z.record(z.string(), z.any())),
      version: types.number(),
      created_at: types.date(),
      updated_at: types.date(),
      scope_mode: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "org_id": "orgId",
        "creator_id": "creatorId",
        "scope_id": "scopeId",
        "rule_metadata": "ruleMetadata",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
        "scope_mode": "scopeMode",
      });
    }),
  );

export function ruleResponseFromJSON(
  jsonString: string,
): SafeParseResult<RuleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RuleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RuleResponse' from JSON`,
  );
}
