/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TokenUsage, TokenUsage$inboundSchema } from "./token-usage.js";

export type SendMessageResponse = {
  /**
   * Session ID
   */
  sessionId: string;
  /**
   * Thread ID
   */
  threadId: string;
  /**
   * AI agent response
   */
  message: string;
  /**
   * Updated message count
   */
  messageCount: number;
  /**
   * Response timestamp
   */
  timestamp: Date;
  /**
   * Token usage for this message
   */
  tokensUsed?: TokenUsage | null | undefined;
  /**
   * Cost in USD for this message
   */
  costUsd?: number | null | undefined;
};

/** @internal */
export const SendMessageResponse$inboundSchema: z.ZodMiniType<
  SendMessageResponse,
  unknown
> = z.pipe(
  z.object({
    session_id: types.string(),
    thread_id: types.string(),
    message: types.string(),
    message_count: types.number(),
    timestamp: types.date(),
    tokens_used: z.optional(z.nullable(TokenUsage$inboundSchema)),
    cost_usd: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "session_id": "sessionId",
      "thread_id": "threadId",
      "message_count": "messageCount",
      "tokens_used": "tokensUsed",
      "cost_usd": "costUsd",
    });
  }),
);

export function sendMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageResponse' from JSON`,
  );
}
