/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreateSessionResponse,
  CreateSessionResponse$inboundSchema,
} from "./create-session-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SessionListResponse = {
  /**
   * List of sessions
   */
  sessions: Array<CreateSessionResponse>;
  /**
   * Total number of sessions
   */
  total: number;
  /**
   * Page size
   */
  limit: number;
  /**
   * Offset
   */
  offset: number;
};

/** @internal */
export const SessionListResponse$inboundSchema: z.ZodMiniType<
  SessionListResponse,
  unknown
> = z.object({
  sessions: z.array(CreateSessionResponse$inboundSchema),
  total: types.number(),
  limit: types.number(),
  offset: types.number(),
});

export function sessionListResponseFromJSON(
  jsonString: string,
): SafeParseResult<SessionListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionListResponse' from JSON`,
  );
}
