/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  EventPreviewDTO,
  EventPreviewDTO$inboundSchema,
} from "./event-preview-dto.js";

export type SpaceStoryDTO = {
  id: number;
  name: string;
  role: string;
  memberCount: number;
  memberGrowth: number;
  activeEvents?: Array<EventPreviewDTO> | undefined;
  ongoingEventsCount: number;
  upcomingEventsCount: number;
  remainingEventsCount: number;
  materialCount: number;
  subspaceCount: number;
  parentSpaceName?: string | null | undefined;
  visibility: number;
};

/** @internal */
export const SpaceStoryDTO$inboundSchema: z.ZodMiniType<
  SpaceStoryDTO,
  unknown
> = z.pipe(
  z.object({
    id: types.number(),
    name: types.string(),
    role: types.string(),
    member_count: types.number(),
    member_growth: types.number(),
    active_events: types.optional(z.array(EventPreviewDTO$inboundSchema)),
    ongoing_events_count: z._default(types.number(), 0),
    upcoming_events_count: z._default(types.number(), 0),
    remaining_events_count: z._default(types.number(), 0),
    material_count: z._default(types.number(), 0),
    subspace_count: z._default(types.number(), 0),
    parent_space_name: z.optional(z.nullable(types.string())),
    visibility: z._default(types.number(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      "member_count": "memberCount",
      "member_growth": "memberGrowth",
      "active_events": "activeEvents",
      "ongoing_events_count": "ongoingEventsCount",
      "upcoming_events_count": "upcomingEventsCount",
      "remaining_events_count": "remainingEventsCount",
      "material_count": "materialCount",
      "subspace_count": "subspaceCount",
      "parent_space_name": "parentSpaceName",
    });
  }),
);

export function spaceStoryDTOFromJSON(
  jsonString: string,
): SafeParseResult<SpaceStoryDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpaceStoryDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpaceStoryDTO' from JSON`,
  );
}
