/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Space role update model
 */
export type SpaceRoleUpdate = {
  name?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export type SpaceRoleUpdate$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const SpaceRoleUpdate$outboundSchema: z.ZodMiniType<
  SpaceRoleUpdate$Outbound,
  SpaceRoleUpdate
> = z.object({
  name: z.optional(z.nullable(z.string())),
  description: z.optional(z.nullable(z.string())),
});

export function spaceRoleUpdateToJSON(
  spaceRoleUpdate: SpaceRoleUpdate,
): string {
  return JSON.stringify(SpaceRoleUpdate$outboundSchema.parse(spaceRoleUpdate));
}
