/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Pydantic model for creating a new space contact.
 */
export type SpaceContactCreate = {
  /**
   * Contact ID to add to space
   */
  contactId: string;
};

/** @internal */
export type SpaceContactCreate$Outbound = {
  contact_id: string;
};

/** @internal */
export const SpaceContactCreate$outboundSchema: z.ZodMiniType<
  SpaceContactCreate$Outbound,
  SpaceContactCreate
> = z.pipe(
  z.object({
    contactId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      contactId: "contact_id",
    });
  }),
);

export function spaceContactCreateToJSON(
  spaceContactCreate: SpaceContactCreate,
): string {
  return JSON.stringify(
    SpaceContactCreate$outboundSchema.parse(spaceContactCreate),
  );
}
