/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SpaceVersionProfile,
  SpaceVersionProfile$inboundSchema,
} from "./space-version-profile.js";

export type SpaceVersionMember = {
  userId: string;
  role: string;
  isActive: boolean;
  joinedAt?: Date | null | undefined;
  profile: SpaceVersionProfile | null;
};

/** @internal */
export const SpaceVersionMember$inboundSchema: z.ZodMiniType<
  SpaceVersionMember,
  unknown
> = z.pipe(
  z.object({
    user_id: types.string(),
    role: types.string(),
    is_active: types.boolean(),
    joined_at: z.optional(z.nullable(types.date())),
    profile: types.nullable(SpaceVersionProfile$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "user_id": "userId",
      "is_active": "isActive",
      "joined_at": "joinedAt",
    });
  }),
);

export function spaceVersionMemberFromJSON(
  jsonString: string,
): SafeParseResult<SpaceVersionMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SpaceVersionMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SpaceVersionMember' from JSON`,
  );
}
