/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Request schema for updating a booking
 */
export type UpdateBookingRequest = {
  /**
   * Booking title
   */
  title: string;
  /**
   * Booking description
   */
  description?: string | null | undefined;
  /**
   * Start datetime
   */
  startDt: Date;
  /**
   * End datetime
   */
  endDt: Date;
  /**
   * Booking status
   */
  status?: string | undefined;
};

/** @internal */
export type UpdateBookingRequest$Outbound = {
  title: string;
  description?: string | null | undefined;
  start_dt: string;
  end_dt: string;
  status: string;
};

/** @internal */
export const UpdateBookingRequest$outboundSchema: z.ZodMiniType<
  UpdateBookingRequest$Outbound,
  UpdateBookingRequest
> = z.pipe(
  z.object({
    title: z.string(),
    description: z.optional(z.nullable(z.string())),
    startDt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    endDt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    status: z._default(z.string(), "confirmed"),
  }),
  z.transform((v) => {
    return remap$(v, {
      startDt: "start_dt",
      endDt: "end_dt",
    });
  }),
);

export function updateBookingRequestToJSON(
  updateBookingRequest: UpdateBookingRequest,
): string {
  return JSON.stringify(
    UpdateBookingRequest$outboundSchema.parse(updateBookingRequest),
  );
}
