/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Request to update space parent
 */
export type UpdateParentRequest = {
  /**
   * New parent ID or null to remove parent
   */
  parentId?: number | null | undefined;
};

/** @internal */
export type UpdateParentRequest$Outbound = {
  parent_id?: number | null | undefined;
};

/** @internal */
export const UpdateParentRequest$outboundSchema: z.ZodMiniType<
  UpdateParentRequest$Outbound,
  UpdateParentRequest
> = z.pipe(
  z.object({
    parentId: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      parentId: "parent_id",
    });
  }),
);

export function updateParentRequestToJSON(
  updateParentRequest: UpdateParentRequest,
): string {
  return JSON.stringify(
    UpdateParentRequest$outboundSchema.parse(updateParentRequest),
  );
}
