/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  WorkflowStatus,
  WorkflowStatus$inboundSchema,
} from "./workflow-status.js";
import { WorkflowType, WorkflowType$inboundSchema } from "./workflow-type.js";

export type WorkflowExecutionResponse = {
  /**
   * Execution ID
   */
  id: string;
  /**
   * Organization ID (null for personal)
   */
  orgId: string | null;
  /**
   * User who started the workflow
   */
  creatorId: string;
  /**
   * Associated session ID
   */
  sessionId: string | null;
  /**
   * Enum representing different workflow types.
   */
  workflowType: WorkflowType;
  /**
   * Workflow name
   */
  workflowName: string;
  /**
   * Input parameters
   */
  inputData: { [k: string]: any };
  /**
   * Output results
   */
  outputData: { [k: string]: any } | null;
  /**
   * Enum representing workflow execution status.
   */
  status: WorkflowStatus;
  /**
   * Error message if failed
   */
  errorMessage: string | null;
  /**
   * Agents used in workflow
   */
  agentsInvolved: Array<string> | null;
  /**
   * Execution time in milliseconds
   */
  executionTimeMs: number | null;
  /**
   * Start timestamp
   */
  startedAt: Date;
  /**
   * Completion timestamp
   */
  completedAt: Date | null;
};

/** @internal */
export const WorkflowExecutionResponse$inboundSchema: z.ZodMiniType<
  WorkflowExecutionResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    org_id: types.nullable(types.string()),
    creator_id: types.string(),
    session_id: types.nullable(types.string()),
    workflow_type: WorkflowType$inboundSchema,
    workflow_name: types.string(),
    input_data: z.record(z.string(), z.any()),
    output_data: types.nullable(z.record(z.string(), z.any())),
    status: WorkflowStatus$inboundSchema,
    error_message: types.nullable(types.string()),
    agents_involved: types.nullable(z.array(types.string())),
    execution_time_ms: types.nullable(types.number()),
    started_at: types.date(),
    completed_at: types.nullable(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "org_id": "orgId",
      "creator_id": "creatorId",
      "session_id": "sessionId",
      "workflow_type": "workflowType",
      "workflow_name": "workflowName",
      "input_data": "inputData",
      "output_data": "outputData",
      "error_message": "errorMessage",
      "agents_involved": "agentsInvolved",
      "execution_time_ms": "executionTimeMs",
      "started_at": "startedAt",
      "completed_at": "completedAt",
    });
  }),
);

export function workflowExecutionResponseFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowExecutionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowExecutionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowExecutionResponse' from JSON`,
  );
}
