"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from typing_extensions import TypedDict


class AppEventDomainEntityEventSpaceInfoTypedDict(TypedDict):
    r"""Comparison model for Space information."""

    id: int
    title: str
    description: str


class AppEventDomainEntityEventSpaceInfo(BaseModel):
    r"""Comparison model for Space information."""

    id: int

    title: str

    description: str
