"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import io
from linebundle_sdk.types import BaseModel, UNSET_SENTINEL
from linebundle_sdk.utils import FieldMetadata, MultipartFormMetadata
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class BodyCreateEventAPIV1EventPostFileTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class BodyCreateEventAPIV1EventPostFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BodyCreateEventAPIV1EventPostTypedDict(TypedDict):
    request: str
    r"""JSON string of CreateEventRequest"""
    file: NotRequired[BodyCreateEventAPIV1EventPostFileTypedDict]
    r"""Optional cover image file"""


class BodyCreateEventAPIV1EventPost(BaseModel):
    request: Annotated[str, FieldMetadata(multipart=True)]
    r"""JSON string of CreateEventRequest"""

    file: Annotated[
        Optional[BodyCreateEventAPIV1EventPostFile],
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ] = None
    r"""Optional cover image file"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
