"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taskmetadata import TaskMetadata, TaskMetadataTypedDict
from linebundle_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CombinedMetadataResponseTypedDict(TypedDict):
    r"""Combined response with all metadata types."""

    triggers: List[TaskMetadataTypedDict]
    conditions: List[TaskMetadataTypedDict]
    actions: List[TaskMetadataTypedDict]


class CombinedMetadataResponse(BaseModel):
    r"""Combined response with all metadata types."""

    triggers: List[TaskMetadata]

    conditions: List[TaskMetadata]

    actions: List[TaskMetadata]
