"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from typing_extensions import TypedDict


class CreateDirectRoomRequestTypedDict(TypedDict):
    other_user_id: str
    r"""User ID to create direct message with"""


class CreateDirectRoomRequest(BaseModel):
    other_user_id: str
    r"""User ID to create direct message with"""
