"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pulsedto import PulseDTO, PulseDTOTypedDict
from .spacestorydto import SpaceStoryDTO, SpaceStoryDTOTypedDict
from linebundle_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DashboardStoryResponseTypedDict(TypedDict):
    pulse: PulseDTOTypedDict
    spaces: List[SpaceStoryDTOTypedDict]
    total_spaces: NotRequired[int]


class DashboardStoryResponse(BaseModel):
    pulse: PulseDTO

    spaces: List[SpaceStoryDTO]

    total_spaces: Optional[int] = 0

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total_spaces"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
