"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteMessageAPIV1ChatMessagesMessageIDDeleteRequestTypedDict(TypedDict):
    message_id: str


class DeleteMessageAPIV1ChatMessagesMessageIDDeleteRequest(BaseModel):
    message_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
