"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventdatefilter import EventDateFilter, EventDateFilterTypedDict
from .eventlocationfilter import EventLocationFilter, EventLocationFilterTypedDict
from .eventrelationshipfilter import (
    EventRelationshipFilter,
    EventRelationshipFilterTypedDict,
)
from .eventrepeatfilter import EventRepeatFilter, EventRepeatFilterTypedDict
from .eventstatusfilter import EventStatusFilter, EventStatusFilterTypedDict
from .eventtextfilter import EventTextFilter, EventTextFilterTypedDict
from linebundle_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class EventAdvancedFiltersTypedDict(TypedDict):
    r"""Complete advanced filtering options for events."""

    date_filters: NotRequired[Nullable[EventDateFilterTypedDict]]
    r"""Date-based filters"""
    text_filters: NotRequired[Nullable[EventTextFilterTypedDict]]
    r"""Text-based filters"""
    status_filters: NotRequired[Nullable[EventStatusFilterTypedDict]]
    r"""Status-based filters"""
    relationship_filters: NotRequired[Nullable[EventRelationshipFilterTypedDict]]
    r"""Relationship-based filters"""
    repeat_filters: NotRequired[Nullable[EventRepeatFilterTypedDict]]
    r"""Recurrence-based filters"""
    location_filters: NotRequired[Nullable[EventLocationFilterTypedDict]]
    r"""Location-based filters"""
    custom_conditions: NotRequired[Nullable[str]]
    r"""JSON string for complex filter conditions using FilterGroup format"""


class EventAdvancedFilters(BaseModel):
    r"""Complete advanced filtering options for events."""

    date_filters: OptionalNullable[EventDateFilter] = UNSET
    r"""Date-based filters"""

    text_filters: OptionalNullable[EventTextFilter] = UNSET
    r"""Text-based filters"""

    status_filters: OptionalNullable[EventStatusFilter] = UNSET
    r"""Status-based filters"""

    relationship_filters: OptionalNullable[EventRelationshipFilter] = UNSET
    r"""Relationship-based filters"""

    repeat_filters: OptionalNullable[EventRepeatFilter] = UNSET
    r"""Recurrence-based filters"""

    location_filters: OptionalNullable[EventLocationFilter] = UNSET
    r"""Location-based filters"""

    custom_conditions: OptionalNullable[str] = UNSET
    r"""JSON string for complex filter conditions using FilterGroup format"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "date_filters",
                "text_filters",
                "status_filters",
                "relationship_filters",
                "repeat_filters",
                "location_filters",
                "custom_conditions",
            ]
        )
        nullable_fields = set(
            [
                "date_filters",
                "text_filters",
                "status_filters",
                "relationship_filters",
                "repeat_filters",
                "location_filters",
                "custom_conditions",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
