"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetSpaceMembersAPIV1SpaceSpaceIDMembersGetRequestTypedDict(TypedDict):
    space_id: int


class GetSpaceMembersAPIV1SpaceSpaceIDMembersGetRequest(BaseModel):
    space_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
