"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetUserAvatarAPIV1UserAvatarUserIDGetRequestTypedDict(TypedDict):
    user_id: str


class GetUserAvatarAPIV1UserAvatarUserIDGetRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
