"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class ListEventVersionsAPIV1EventEventIDVersionsGetRequestTypedDict(TypedDict):
    event_id: int


class ListEventVersionsAPIV1EventEventIDVersionsGetRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
