"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from linebundle_sdk.types import BaseModel
from typing_extensions import TypedDict


class MemberResponseTypedDict(TypedDict):
    id: str
    room_id: str
    user_id: str
    role: str
    created_at: datetime
    updated_at: datetime


class MemberResponse(BaseModel):
    id: str

    room_id: str

    user_id: str

    role: str

    created_at: datetime

    updated_at: datetime
