"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from linebundle_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class OrgCostSummaryTypedDict(TypedDict):
    org_id: str
    r"""Organization ID"""
    total_cost_usd: float
    r"""Total cost across all sessions"""
    total_tokens: int
    r"""Total tokens used"""
    session_count: int
    r"""Number of sessions"""
    user_count: int
    r"""Number of unique users"""
    start_date: NotRequired[Nullable[datetime]]
    r"""Start date filter"""
    end_date: NotRequired[Nullable[datetime]]
    r"""End date filter"""


class OrgCostSummary(BaseModel):
    org_id: str
    r"""Organization ID"""

    total_cost_usd: float
    r"""Total cost across all sessions"""

    total_tokens: int
    r"""Total tokens used"""

    session_count: int
    r"""Number of sessions"""

    user_count: int
    r"""Number of unique users"""

    start_date: OptionalNullable[datetime] = UNSET
    r"""Start date filter"""

    end_date: OptionalNullable[datetime] = UNSET
    r"""End date filter"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start_date", "end_date"])
        nullable_fields = set(["start_date", "end_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
