"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .geteventlistresponse import GetEventListResponse, GetEventListResponseTypedDict
from .paginationmeta import PaginationMeta, PaginationMetaTypedDict
from linebundle_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PaginatedEventListResponseTypedDict(TypedDict):
    items: List[GetEventListResponseTypedDict]
    meta: PaginationMetaTypedDict


class PaginatedEventListResponse(BaseModel):
    items: List[GetEventListResponse]

    meta: PaginationMeta
