"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class RemovePermissionEndpointAPIV1RolesRoleIDPermissionsPermissionCodeDeleteRequestTypedDict(
    TypedDict
):
    role_id: str
    permission_code: str


class RemovePermissionEndpointAPIV1RolesRoleIDPermissionsPermissionCodeDeleteRequest(
    BaseModel
):
    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    permission_code: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
