"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .roomtype import RoomType
from datetime import datetime
from linebundle_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RoomResponseTypedDict(TypedDict):
    id: str
    room_type: RoomType
    name: Nullable[str]
    description: Nullable[str]
    visibility: int
    creator_id: str
    created_at: datetime
    updated_at: datetime
    org_id: NotRequired[Nullable[str]]
    metadata: NotRequired[Dict[str, Any]]
    r"""Named schema for arbitrary key-value metadata on chat rooms and messages.

    Using ``RootModel`` instead of an inline ``dict[str, Any]`` ensures FastAPI/Pydantic
    emits a single named ``ChatMetadata`` component (``$ref``) in the OpenAPI spec,
    preventing Speakeasy from flagging duplicate anonymous schemas.
    """


class RoomResponse(BaseModel):
    id: str

    room_type: RoomType

    name: Nullable[str]

    description: Nullable[str]

    visibility: int

    creator_id: str

    created_at: datetime

    updated_at: datetime

    org_id: OptionalNullable[str] = UNSET

    metadata: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="metadata_")] = (
        None
    )
    r"""Named schema for arbitrary key-value metadata on chat rooms and messages.

    Using ``RootModel`` instead of an inline ``dict[str, Any]`` ensures FastAPI/Pydantic
    emits a single named ``ChatMetadata`` component (``$ref``) in the OpenAPI spec,
    preventing Speakeasy from flagging duplicate anonymous schemas.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["org_id", "metadata_"])
        nullable_fields = set(["org_id", "name", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    RoomResponse.model_rebuild()
except NameError:
    pass
