"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from typing_extensions import TypedDict


class SpaceContactCreateTypedDict(TypedDict):
    r"""Pydantic model for creating a new space contact."""

    contact_id: str
    r"""Contact ID to add to space"""


class SpaceContactCreate(BaseModel):
    r"""Pydantic model for creating a new space contact."""

    contact_id: str
    r"""Contact ID to add to space"""
