"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from linebundle_sdk.types import BaseModel
from typing_extensions import TypedDict


class TokenUsageTypedDict(TypedDict):
    input: int
    r"""Input tokens consumed"""
    output: int
    r"""Output tokens generated"""
    total: int
    r"""Total tokens (input + output)"""


class TokenUsage(BaseModel):
    input: int
    r"""Input tokens consumed"""

    output: int
    r"""Output tokens generated"""

    total: int
    r"""Total tokens (input + output)"""
