"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .locationupdateschema import LocationUpdateSchema, LocationUpdateSchemaTypedDict
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateEventLocationAPIV1EventsEventIDLocationPutRequestTypedDict(TypedDict):
    event_id: int
    body: LocationUpdateSchemaTypedDict


class UpdateEventLocationAPIV1EventsEventIDLocationPutRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        LocationUpdateSchema,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
