"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .spacerole import SpaceRole
from linebundle_sdk.types import BaseModel
from typing_extensions import TypedDict


class UpdateSpaceMemberRoleRequestTypedDict(TypedDict):
    r"""Request model for updating a space member's role"""

    role: SpaceRole
    r"""Space roles with hierarchical permissions"""


class UpdateSpaceMemberRoleRequest(BaseModel):
    r"""Request model for updating a space member's role"""

    role: SpaceRole
    r"""Space roles with hierarchical permissions"""
