"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createeventrequest import CreateEventRequest, CreateEventRequestTypedDict
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateEventAPIV1EventEventIDPutRequestTypedDict(TypedDict):
    event_id: int
    body: CreateEventRequestTypedDict


class UpdateEventAPIV1EventEventIDPutRequest(BaseModel):
    event_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        CreateEventRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
