"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateorganizationrequest import (
    UpdateOrganizationRequest,
    UpdateOrganizationRequestTypedDict,
)
from linebundle_sdk.types import BaseModel
from linebundle_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateOrganizationEndpointAPIV1OrganizationsOrgIDPutRequestTypedDict(TypedDict):
    org_id: str
    body: UpdateOrganizationRequestTypedDict


class UpdateOrganizationEndpointAPIV1OrganizationsOrgIDPutRequest(BaseModel):
    org_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        UpdateOrganizationRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
