/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyticGetAnalyticTotalsApiV1AnalyticCountsGet } from "../funcs/analytic-get-analytic-totals-api-v1-analytic-counts-get.js";
import { analyticGetDashboardAnalyticsApiV1AnalyticDashboardGet } from "../funcs/analytic-get-dashboard-analytics-api-v1-analytic-dashboard-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Analytic extends ClientSDK {
  /**
   * Get Analytic Totals
   */
  async getAnalyticTotalsApiV1AnalyticCountsGet(
    options?: RequestOptions,
  ): Promise<models.GetAnalyticTotalsDto> {
    return unwrapAsync(analyticGetAnalyticTotalsApiV1AnalyticCountsGet(
      this,
      options,
    ));
  }

  /**
   * Get Dashboard Analytics
   */
  async getDashboardAnalyticsApiV1AnalyticDashboardGet(
    options?: RequestOptions,
  ): Promise<models.DashboardStoryResponse> {
    return unwrapAsync(analyticGetDashboardAnalyticsApiV1AnalyticDashboardGet(
      this,
      options,
    ));
  }
}
