/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTimelineCreateMilestoneApiV1EventEventIdTimelineMilestonesPost } from "../funcs/event-timeline-create-milestone-api-v1-event-event-id-timeline-milestones-post.js";
import { eventTimelineGetPublishedTimelineApiV1EventEventIdTimelinePublishedGet } from "../funcs/event-timeline-get-published-timeline-api-v1-event-event-id-timeline-published-get.js";
import { eventTimelineGetTimelineApiV1EventEventIdTimelineGet } from "../funcs/event-timeline-get-timeline-api-v1-event-event-id-timeline-get.js";
import { eventTimelineLinkMilestoneApiV1EventEventIdTimelineLinkPost } from "../funcs/event-timeline-link-milestone-api-v1-event-event-id-timeline-link-post.js";
import { eventTimelineUnlinkMilestoneApiV1EventEventIdTimelineMilestoneEventIdDelete } from "../funcs/event-timeline-unlink-milestone-api-v1-event-event-id-timeline-milestone-event-id-delete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EventTimeline extends ClientSDK {
  /**
   * Get event timeline
   *
   * @remarks
   * Retrieve all milestones linked to a base event.
   */
  async getTimelineApiV1EventEventIdTimelineGet(
    security: operations.GetTimelineApiV1EventEventIdTimelineGetSecurity,
    request: operations.GetTimelineApiV1EventEventIdTimelineGetRequest,
    options?: RequestOptions,
  ): Promise<Array<models.EventRead>> {
    return unwrapAsync(eventTimelineGetTimelineApiV1EventEventIdTimelineGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get published event timeline
   *
   * @remarks
   * Retrieve published milestones for a base event's published version. Returns only milestones that were linked at publish time AND are themselves published.
   */
  async getPublishedTimelineApiV1EventEventIdTimelinePublishedGet(
    request:
      operations.GetPublishedTimelineApiV1EventEventIdTimelinePublishedGetRequest,
    options?: RequestOptions,
  ): Promise<Array<models.EventRead>> {
    return unwrapAsync(
      eventTimelineGetPublishedTimelineApiV1EventEventIdTimelinePublishedGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create and link milestone
   *
   * @remarks
   * Create a new event and automatically link it as a milestone.
   */
  async createMilestoneApiV1EventEventIdTimelineMilestonesPost(
    security:
      operations.CreateMilestoneApiV1EventEventIdTimelineMilestonesPostSecurity,
    request:
      operations.CreateMilestoneApiV1EventEventIdTimelineMilestonesPostRequest,
    options?: RequestOptions,
  ): Promise<models.EventRead> {
    return unwrapAsync(
      eventTimelineCreateMilestoneApiV1EventEventIdTimelineMilestonesPost(
        this,
        security,
        request,
        options,
      ),
    );
  }

  /**
   * Link existing event
   *
   * @remarks
   * Link an existing event as a milestone to a base event.
   */
  async linkMilestoneApiV1EventEventIdTimelineLinkPost(
    security: operations.LinkMilestoneApiV1EventEventIdTimelineLinkPostSecurity,
    request: operations.LinkMilestoneApiV1EventEventIdTimelineLinkPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(
      eventTimelineLinkMilestoneApiV1EventEventIdTimelineLinkPost(
        this,
        security,
        request,
        options,
      ),
    );
  }

  /**
   * Unlink milestone
   *
   * @remarks
   * Remove a milestone link without deleting the event.
   */
  async unlinkMilestoneApiV1EventEventIdTimelineMilestoneEventIdDelete(
    security:
      operations.UnlinkMilestoneApiV1EventEventIdTimelineMilestoneEventIdDeleteSecurity,
    request:
      operations.UnlinkMilestoneApiV1EventEventIdTimelineMilestoneEventIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(
      eventTimelineUnlinkMilestoneApiV1EventEventIdTimelineMilestoneEventIdDelete(
        this,
        security,
        request,
        options,
      ),
    );
  }
}
