/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTimezonesValidate } from "../funcs/event-timezones-validate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EventTimezones extends ClientSDK {
  /**
   * Validate Timezone
   *
   * @remarks
   * Validate a specific timezone string.
   *
   * Args:
   *     timezone: Timezone string to validate (query parameter)
   *
   * Returns:
   *     Dictionary containing:
   *     - valid: Boolean indicating if timezone is valid
   *     - timezone: The validated timezone string
   *     - suggestions: List of similar timezones if invalid (empty if valid)
   */
  async validate(
    request: operations.ValidateTimezoneApiV1EventTimezonesValidateGetRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(eventTimezonesValidate(
      this,
      request,
      options,
    ));
  }
}
