/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresGet } from "../funcs/features-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Features extends ClientSDK {
  /**
   * Get Feature Flags
   *
   * @remarks
   * Get current feature flag status for frontend clients.
   */
  async get(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(featuresGet(
      this,
      options,
    ));
  }
}
