/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthNotificationsCheck } from "../funcs/health-notifications-check.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class HealthNotifications extends ClientSDK {
  /**
   * Notification Health Check
   *
   * @remarks
   * Health check endpoint for notification services configuration.
   */
  async check(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(healthNotificationsCheck(
      this,
      options,
    ));
  }
}
