/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsHandleOrgCreated } from "../funcs/integrations-handle-org-created.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Integrations extends ClientSDK {
  /**
   * Webhook from Zitadel for organization creation
   *
   * @remarks
   * Receives an authenticated JWT webhook payload from a Zitadel Action
   * when a new organization is created.
   */
  async handleOrgCreated(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(integrationsHandleOrgCreated(
      this,
      options,
    ));
  }
}
