/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicEventsGetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGet } from "../funcs/public-events-get-latest-public-event-version-api-v1-public-event-event-id-versions-latest-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PublicEvents extends ClientSDK {
  /**
   * Get Latest Event Version (Public Access)
   *
   * @remarks
   * Get the most recent published version of an event. Supports unauthenticated access for PUBLIC events.
   */
  async getLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGet(
    request:
      operations.GetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGetRequest,
    options?: RequestOptions,
  ): Promise<models.EventVersionRead> {
    return unwrapAsync(
      publicEventsGetLatestPublicEventVersionApiV1PublicEventEventIdVersionsLatestGet(
        this,
        request,
        options,
      ),
    );
  }
}
