/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { realtimeConnect } from "../funcs/realtime-connect.js";
import { realtimeGetInfo } from "../funcs/realtime-get-info.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Realtime extends ClientSDK {
  /**
   * Realtime WebSocket protocol info
   *
   * @remarks
   * Get WebSocket protocol information.
   *
   * Returns documentation about the WebSocket endpoint including:
   * - Connection endpoint
   * - Authentication requirements
   * - Protocol details
   * - ACK message format
   *
   * Returns:
   *     dict: WebSocket protocol information
   */
  async getInfo(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(realtimeGetInfo(
      this,
      options,
    ));
  }

  /**
   * Establish realtime WebSocket connection (upgrade)
   *
   * @remarks
   * Upgrades to WebSocket at this path (subprotocol: json).
   *
   * Requires valid authenticated user & tenant context. Server sends single ACK then may push events.
   */
  async connect(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(realtimeConnect(
      this,
      options,
    ));
  }
}
