/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AiAgent } from "./ai-agent.js";
import { AiAgents } from "./ai-agents.js";
import { AiWorkflows } from "./ai-workflows.js";
import { Ai } from "./ai.js";
import { Analytic } from "./analytic.js";
import { AuditLogs } from "./audit-logs.js";
import { AuthContexts } from "./auth-contexts.js";
import { AutomationCron } from "./automation-cron.js";
import { AutomationMetadata } from "./automation-metadata.js";
import { AutomationRules } from "./automation-rules.js";
import { Booking } from "./booking.js";
import { Bookings } from "./bookings.js";
import { ChatMessages } from "./chat-messages.js";
import { ChatRooms } from "./chat-rooms.js";
import { Contacts } from "./contacts.js";
import { CustomRoles } from "./custom-roles.js";
import { EventAttendees } from "./event-attendees.js";
import { EventDocuments } from "./event-documents.js";
import { EventLocation } from "./event-location.js";
import { EventTimeline } from "./event-timeline.js";
import { EventTimezones } from "./event-timezones.js";
import { Event } from "./event.js";
import { Events } from "./events.js";
import { Features } from "./features.js";
import { HealthNotifications } from "./health-notifications.js";
import { Health } from "./health.js";
import { IntegrationUser } from "./integration-user.js";
import { Integration } from "./integration.js";
import { Integrations } from "./integrations.js";
import { Metrics } from "./metrics.js";
import { Organizations } from "./organizations.js";
import { Permissions } from "./permissions.js";
import { Place } from "./place.js";
import { Places } from "./places.js";
import { PublicEvents } from "./public-events.js";
import { PublicSpaces } from "./public-spaces.js";
import { Realtime } from "./realtime.js";
import { Roles } from "./roles.js";
import { Sentry } from "./sentry.js";
import { SpaceContacts } from "./space-contacts.js";
import { SpaceDocuments } from "./space-documents.js";
import { SpaceEvents } from "./space-events.js";
import { SpaceMemberRoles } from "./space-member-roles.js";
import { SpaceRoles } from "./space-roles.js";
import { Space } from "./space.js";
import { Spaces } from "./spaces.js";
import { User } from "./user.js";
import { Users } from "./users.js";

export class Linebundle extends ClientSDK {
  private _user?: User;
  get user(): User {
    return (this._user ??= new User(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }

  private _authContexts?: AuthContexts;
  get authContexts(): AuthContexts {
    return (this._authContexts ??= new AuthContexts(this._options));
  }

  private _auditLogs?: AuditLogs;
  get auditLogs(): AuditLogs {
    return (this._auditLogs ??= new AuditLogs(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _event?: Event;
  get event(): Event {
    return (this._event ??= new Event(this._options));
  }

  private _eventTimezones?: EventTimezones;
  get eventTimezones(): EventTimezones {
    return (this._eventTimezones ??= new EventTimezones(this._options));
  }

  private _eventAttendees?: EventAttendees;
  get eventAttendees(): EventAttendees {
    return (this._eventAttendees ??= new EventAttendees(this._options));
  }

  private _eventTimeline?: EventTimeline;
  get eventTimeline(): EventTimeline {
    return (this._eventTimeline ??= new EventTimeline(this._options));
  }

  private _eventDocuments?: EventDocuments;
  get eventDocuments(): EventDocuments {
    return (this._eventDocuments ??= new EventDocuments(this._options));
  }

  private _eventLocation?: EventLocation;
  get eventLocation(): EventLocation {
    return (this._eventLocation ??= new EventLocation(this._options));
  }

  private _space?: Space;
  get space(): Space {
    return (this._space ??= new Space(this._options));
  }

  private _spaces?: Spaces;
  get spaces(): Spaces {
    return (this._spaces ??= new Spaces(this._options));
  }

  private _spaceRoles?: SpaceRoles;
  get spaceRoles(): SpaceRoles {
    return (this._spaceRoles ??= new SpaceRoles(this._options));
  }

  private _spaceMemberRoles?: SpaceMemberRoles;
  get spaceMemberRoles(): SpaceMemberRoles {
    return (this._spaceMemberRoles ??= new SpaceMemberRoles(this._options));
  }

  private _spaceContacts?: SpaceContacts;
  get spaceContacts(): SpaceContacts {
    return (this._spaceContacts ??= new SpaceContacts(this._options));
  }

  private _spaceEvents?: SpaceEvents;
  get spaceEvents(): SpaceEvents {
    return (this._spaceEvents ??= new SpaceEvents(this._options));
  }

  private _spaceDocuments?: SpaceDocuments;
  get spaceDocuments(): SpaceDocuments {
    return (this._spaceDocuments ??= new SpaceDocuments(this._options));
  }

  private _places?: Places;
  get places(): Places {
    return (this._places ??= new Places(this._options));
  }

  private _place?: Place;
  get place(): Place {
    return (this._place ??= new Place(this._options));
  }

  private _analytic?: Analytic;
  get analytic(): Analytic {
    return (this._analytic ??= new Analytic(this._options));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _customRoles?: CustomRoles;
  get customRoles(): CustomRoles {
    return (this._customRoles ??= new CustomRoles(this._options));
  }

  private _roles?: Roles;
  get roles(): Roles {
    return (this._roles ??= new Roles(this._options));
  }

  private _permissions?: Permissions;
  get permissions(): Permissions {
    return (this._permissions ??= new Permissions(this._options));
  }

  private _bookings?: Bookings;
  get bookings(): Bookings {
    return (this._bookings ??= new Bookings(this._options));
  }

  private _booking?: Booking;
  get booking(): Booking {
    return (this._booking ??= new Booking(this._options));
  }

  private _chatRooms?: ChatRooms;
  get chatRooms(): ChatRooms {
    return (this._chatRooms ??= new ChatRooms(this._options));
  }

  private _chatMessages?: ChatMessages;
  get chatMessages(): ChatMessages {
    return (this._chatMessages ??= new ChatMessages(this._options));
  }

  private _aiAgent?: AiAgent;
  get aiAgent(): AiAgent {
    return (this._aiAgent ??= new AiAgent(this._options));
  }

  private _ai?: Ai;
  get ai(): Ai {
    return (this._ai ??= new Ai(this._options));
  }

  private _aiAgents?: AiAgents;
  get aiAgents(): AiAgents {
    return (this._aiAgents ??= new AiAgents(this._options));
  }

  private _aiWorkflows?: AiWorkflows;
  get aiWorkflows(): AiWorkflows {
    return (this._aiWorkflows ??= new AiWorkflows(this._options));
  }

  private _contacts?: Contacts;
  get contacts(): Contacts {
    return (this._contacts ??= new Contacts(this._options));
  }

  private _automationRules?: AutomationRules;
  get automationRules(): AutomationRules {
    return (this._automationRules ??= new AutomationRules(this._options));
  }

  private _automationMetadata?: AutomationMetadata;
  get automationMetadata(): AutomationMetadata {
    return (this._automationMetadata ??= new AutomationMetadata(this._options));
  }

  private _automationCron?: AutomationCron;
  get automationCron(): AutomationCron {
    return (this._automationCron ??= new AutomationCron(this._options));
  }

  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _integrations?: Integrations;
  get integrations(): Integrations {
    return (this._integrations ??= new Integrations(this._options));
  }

  private _integration?: Integration;
  get integration(): Integration {
    return (this._integration ??= new Integration(this._options));
  }

  private _integrationUser?: IntegrationUser;
  get integrationUser(): IntegrationUser {
    return (this._integrationUser ??= new IntegrationUser(this._options));
  }

  private _publicEvents?: PublicEvents;
  get publicEvents(): PublicEvents {
    return (this._publicEvents ??= new PublicEvents(this._options));
  }

  private _publicSpaces?: PublicSpaces;
  get publicSpaces(): PublicSpaces {
    return (this._publicSpaces ??= new PublicSpaces(this._options));
  }

  private _sentry?: Sentry;
  get sentry(): Sentry {
    return (this._sentry ??= new Sentry(this._options));
  }

  private _healthNotifications?: HealthNotifications;
  get healthNotifications(): HealthNotifications {
    return (this._healthNotifications ??= new HealthNotifications(
      this._options,
    ));
  }

  private _metrics?: Metrics;
  get metrics(): Metrics {
    return (this._metrics ??= new Metrics(this._options));
  }

  private _features?: Features;
  get features(): Features {
    return (this._features ??= new Features(this._options));
  }

  private _realtime?: Realtime;
  get realtime(): Realtime {
    return (this._realtime ??= new Realtime(this._options));
  }
}
