/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sentryTriggerError } from "../funcs/sentry-trigger-error.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Sentry extends ClientSDK {
  /**
   * Trigger Sentry Error
   *
   * @remarks
   * Test endpoint to verify Sentry integration.
   * This endpoint intentionally raises an error to test error tracking.
   */
  async triggerError(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(sentryTriggerError(
      this,
      options,
    ));
  }
}
