/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { spaceAddSpaceMemberApiV1SpaceSpaceIdMembersPost } from "../funcs/space-add-space-member-api-v1-space-space-id-members-post.js";
import { spaceArchiveSpaceApiV1SpaceSpaceIdArchivePatch } from "../funcs/space-archive-space-api-v1-space-space-id-archive-patch.js";
import {
  spaceAssignPermissionToSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPost,
} from "../funcs/space-assign-permission-to-space-role-api-v1-space-spaces-space-id-roles-role-id-permissions-post.js";
import { spaceAssignUserToSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesPost } from "../funcs/space-assign-user-to-space-role-api-v1-space-spaces-space-id-members-user-id-roles-post.js";
import { spaceBulkUpdateSpaceParentApiV1SpaceBulkParentPatch } from "../funcs/space-bulk-update-space-parent-api-v1-space-bulk-parent-patch.js";
import { spaceCompareSpaceVersionsApiV1SpaceSpaceIdVersionsCompareGet } from "../funcs/space-compare-space-versions-api-v1-space-space-id-versions-compare-get.js";
import { spaceCreateSpaceApiV1SpacePost } from "../funcs/space-create-space-api-v1-space-post.js";
import { spaceCreateSpaceRoleApiV1SpaceSpacesSpaceIdRolesPost } from "../funcs/space-create-space-role-api-v1-space-spaces-space-id-roles-post.js";
import { spaceCreateSpaceWithParentApiV1SpaceWithParentPost } from "../funcs/space-create-space-with-parent-api-v1-space-with-parent-post.js";
import { spaceDeleteSpaceApiV1SpaceSpaceIdDelete } from "../funcs/space-delete-space-api-v1-space-space-id-delete.js";
import { spaceDeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDelete } from "../funcs/space-delete-space-role-api-v1-space-spaces-space-id-roles-role-id-delete.js";
import { spaceDetachSpaceFromParentApiV1SpaceSpaceIdParentDelete } from "../funcs/space-detach-space-from-parent-api-v1-space-space-id-parent-delete.js";
import { spaceGetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGet } from "../funcs/space-get-joinable-spaces-by-user-api-v1-space-by-user-user-id-joinable-get.js";
import { spaceGetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGet } from "../funcs/space-get-latest-space-version-api-v1-space-space-id-versions-latest-get.js";
import { spaceGetSpaceByIdApiV1SpaceSpaceIdGet } from "../funcs/space-get-space-by-id-api-v1-space-space-id-get.js";
import { spaceGetSpaceChildrenApiV1SpaceSpaceIdChildrenGet } from "../funcs/space-get-space-children-api-v1-space-space-id-children-get.js";
import { spaceGetSpaceHierarchyApiV1SpaceSpaceIdHierarchyGet } from "../funcs/space-get-space-hierarchy-api-v1-space-space-id-hierarchy-get.js";
import { spaceGetSpaceListApiV1SpaceGet } from "../funcs/space-get-space-list-api-v1-space-get.js";
import { spaceGetSpaceMembersApiV1SpaceSpaceIdMembersGet } from "../funcs/space-get-space-members-api-v1-space-space-id-members-get.js";
import { spaceGetSpaceParentApiV1SpaceSpaceIdParentGet } from "../funcs/space-get-space-parent-api-v1-space-space-id-parent-get.js";
import { spaceGetSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdGet } from "../funcs/space-get-space-role-api-v1-space-spaces-space-id-roles-role-id-get.js";
import { spaceGetSpaceVersionApiV1SpaceSpaceIdVersionsVersionNumberGet } from "../funcs/space-get-space-version-api-v1-space-space-id-versions-version-number-get.js";
import { spaceGetUserSpaceRolesApiV1SpaceSpacesSpaceIdMembersUserIdRolesGet } from "../funcs/space-get-user-space-roles-api-v1-space-spaces-space-id-members-user-id-roles-get.js";
import { spaceJoinSpaceApiV1SpaceSpaceIdJoinPost } from "../funcs/space-join-space-api-v1-space-space-id-join-post.js";
import { spaceListSpaceRolesApiV1SpaceSpacesSpaceIdRolesGet } from "../funcs/space-list-space-roles-api-v1-space-spaces-space-id-roles-get.js";
import { spaceListSpaceVersionsApiV1SpaceSpaceIdVersionsGet } from "../funcs/space-list-space-versions-api-v1-space-space-id-versions-get.js";
import { spacePublishSpaceApiV1SpaceSpaceIdPublishPatch } from "../funcs/space-publish-space-api-v1-space-space-id-publish-patch.js";
import { spacePublishSpaceApiV1SpaceSpaceIdPublishPost } from "../funcs/space-publish-space-api-v1-space-space-id-publish-post.js";
import {
  spaceRemovePermissionFromSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPermissionIdDelete,
} from "../funcs/space-remove-permission-from-space-role-api-v1-space-spaces-space-id-roles-role-id-permissions-permission-id-delete.js";
import { spaceRemoveSpaceMemberApiV1SpaceSpaceIdMembersUserIdDelete } from "../funcs/space-remove-space-member-api-v1-space-space-id-members-user-id-delete.js";
import {
  spaceRemoveUserFromSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesSpaceRoleIdDelete,
} from "../funcs/space-remove-user-from-space-role-api-v1-space-spaces-space-id-members-user-id-roles-space-role-id-delete.js";
import { spaceRollbackSpaceApiV1SpaceSpaceIdRollbackPost } from "../funcs/space-rollback-space-api-v1-space-space-id-rollback-post.js";
import { spaceTestAuthApiV1SpaceTestAuthGet } from "../funcs/space-test-auth-api-v1-space-test-auth-get.js";
import { spaceTransferSpaceApiV1SpaceSpaceIdTransferPost } from "../funcs/space-transfer-space-api-v1-space-space-id-transfer-post.js";
import { spaceUnpublishSpaceApiV1SpaceSpaceIdUnpublishPost } from "../funcs/space-unpublish-space-api-v1-space-space-id-unpublish-post.js";
import { spaceUpdateSpaceApiV1SpaceSpaceIdPut } from "../funcs/space-update-space-api-v1-space-space-id-put.js";
import { spaceUpdateSpaceMemberRoleApiV1SpaceSpaceIdMembersUserIdPatch } from "../funcs/space-update-space-member-role-api-v1-space-space-id-members-user-id-patch.js";
import { spaceUpdateSpaceParentApiV1SpaceSpaceIdParentPatch } from "../funcs/space-update-space-parent-api-v1-space-space-id-parent-patch.js";
import { spaceUpdateSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPut } from "../funcs/space-update-space-role-api-v1-space-spaces-space-id-roles-role-id-put.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Space extends ClientSDK {
  /**
   * Test Auth
   *
   * @remarks
   * Test endpoint to verify authentication
   */
  async testAuthApiV1SpaceTestAuthGet(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(spaceTestAuthApiV1SpaceTestAuthGet(
      this,
      options,
    ));
  }

  /**
   * Get Space List
   */
  async getSpaceListApiV1SpaceGet(
    request?: operations.GetSpaceListApiV1SpaceGetRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PaginatedSpaceListResponseDTO> {
    return unwrapAsync(spaceGetSpaceListApiV1SpaceGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Space
   */
  async createSpaceApiV1SpacePost(
    request: models.CreateSpaceRequest,
    options?: RequestOptions,
  ): Promise<models.CreateSpaceResponseDTO> {
    return unwrapAsync(spaceCreateSpaceApiV1SpacePost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space By Id
   */
  async getSpaceByIdApiV1SpaceSpaceIdGet(
    request: operations.GetSpaceByIdApiV1SpaceSpaceIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.GetSpaceListResponseDTO> {
    return unwrapAsync(spaceGetSpaceByIdApiV1SpaceSpaceIdGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Space
   */
  async updateSpaceApiV1SpaceSpaceIdPut(
    request: operations.UpdateSpaceApiV1SpaceSpaceIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.UpdateSpaceResponseDTO> {
    return unwrapAsync(spaceUpdateSpaceApiV1SpaceSpaceIdPut(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Space
   */
  async deleteSpaceApiV1SpaceSpaceIdDelete(
    request: operations.DeleteSpaceApiV1SpaceSpaceIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(spaceDeleteSpaceApiV1SpaceSpaceIdDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Space With Parent
   *
   * @remarks
   * Create a space with parent relationship and inheritance settings
   */
  async createSpaceWithParentApiV1SpaceWithParentPost(
    request: models.CreateSpaceWithParentRequest,
    options?: RequestOptions,
  ): Promise<models.CreateSpaceResponseDTO> {
    return unwrapAsync(spaceCreateSpaceWithParentApiV1SpaceWithParentPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Publish space
   *
   * @remarks
   * Publish current space state as immutable version for community discovery
   */
  async publishSpaceApiV1SpaceSpaceIdPublishPost(
    request: operations.PublishSpaceApiV1SpaceSpaceIdPublishPostRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceVersionRead> {
    return unwrapAsync(spacePublishSpaceApiV1SpaceSpaceIdPublishPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Publish Space
   */
  async publishSpaceApiV1SpaceSpaceIdPublishPatch(
    request: operations.PublishSpaceApiV1SpaceSpaceIdPublishPatchRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(spacePublishSpaceApiV1SpaceSpaceIdPublishPatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive Space
   */
  async archiveSpaceApiV1SpaceSpaceIdArchivePatch(
    request: operations.ArchiveSpaceApiV1SpaceSpaceIdArchivePatchRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(spaceArchiveSpaceApiV1SpaceSpaceIdArchivePatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space Members
   *
   * @remarks
   * Get all members of a space
   */
  async getSpaceMembersApiV1SpaceSpaceIdMembersGet(
    request: operations.GetSpaceMembersApiV1SpaceSpaceIdMembersGetRequest,
    options?: RequestOptions,
  ): Promise<Array<models.SpaceMemberResponse>> {
    return unwrapAsync(spaceGetSpaceMembersApiV1SpaceSpaceIdMembersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Add Space Member
   *
   * @remarks
   * Add a member to a space
   */
  async addSpaceMemberApiV1SpaceSpaceIdMembersPost(
    request: operations.AddSpaceMemberApiV1SpaceSpaceIdMembersPostRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceMemberResponse> {
    return unwrapAsync(spaceAddSpaceMemberApiV1SpaceSpaceIdMembersPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove Space Member
   *
   * @remarks
   * Remove a member from a space
   */
  async removeSpaceMemberApiV1SpaceSpaceIdMembersUserIdDelete(
    request:
      operations.RemoveSpaceMemberApiV1SpaceSpaceIdMembersUserIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(
      spaceRemoveSpaceMemberApiV1SpaceSpaceIdMembersUserIdDelete(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Update Space Member Role
   *
   * @remarks
   * Update a space member's role
   */
  async updateSpaceMemberRoleApiV1SpaceSpaceIdMembersUserIdPatch(
    request:
      operations.UpdateSpaceMemberRoleApiV1SpaceSpaceIdMembersUserIdPatchRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceMemberResponse> {
    return unwrapAsync(
      spaceUpdateSpaceMemberRoleApiV1SpaceSpaceIdMembersUserIdPatch(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Joinable Spaces By User
   *
   * @remarks
   * Get spaces owned by a user that the current viewer can join.
   *
   * This endpoint returns spaces where the target user is an owner and the current
   * viewer has permission to join based on visibility rules:
   * - PUBLIC: Always visible to all users
   * - TENANT: Visible only to users in the same organization
   * - MEMBERS_ONLY: Excluded from joinable list (requires approval)
   *
   * Args:
   *     user_id: UUID string of the user whose spaces to retrieve
   *     limit: Maximum number of spaces to return (default: 10, max: 12)
   *     prev: Previous ID for cursor-based pagination
   *     sort_by: Field to sort by (default: "created_at")
   *     sort_order: Sort order - "asc" or "desc" (default: "desc")
   *
   * Returns:
   *     List[GetSpaceListResponseDTO]: List of joinable spaces
   *
   * Raises:
   *     HTTPException: 401 for unauthorized access, 500 for server errors
   */
  async getJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGet(
    request:
      operations.GetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGetRequest,
    options?: RequestOptions,
  ): Promise<Array<models.GetSpaceListResponseDTO>> {
    return unwrapAsync(
      spaceGetJoinableSpacesByUserApiV1SpaceByUserUserIdJoinableGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Join Space
   *
   * @remarks
   * Self-join the current user to a space if permitted.
   *
   * This endpoint allows the current user to join a space based on visibility rules:
   * - PUBLIC: Anyone can join
   * - TENANT: Only users in the same organization can join
   * - MEMBERS_ONLY: Requires approval (returns 403)
   *
   * Args:
   *     space_id: ID of the space to join
   *
   * Returns:
   *     SpaceMemberResponse: Membership information after successful join
   *
   * Raises:
   *     HTTPException:
   *         - 404: Space not found
   *         - 403: Permission denied (wrong tenant or members-only space)
   *         - 409: Already a member
   *         - 500: Server error
   */
  async joinSpaceApiV1SpaceSpaceIdJoinPost(
    request: operations.JoinSpaceApiV1SpaceSpaceIdJoinPostRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceMemberResponse> {
    return unwrapAsync(spaceJoinSpaceApiV1SpaceSpaceIdJoinPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Transfer Space
   *
   * @remarks
   * Transfer a personal space to an organization.
   *
   * This endpoint allows the creator of a personal space to transfer ownership
   * to an organization they are a member of with owner or admin privileges.
   *
   * Requirements:
   * - Space must be personal (org_id IS NULL)
   * - Caller must be the space creator
   * - Caller must be owner or admin of the target organization
   *
   * Args:
   *     space_id: ID of the space to transfer
   *     request: Transfer request containing target_org_id
   *
   * Returns:
   *     TransferSpaceResponse: Transfer status and metadata
   *
   * Raises:
   *     HTTPException:
   *         - 400: Invalid request (already org-scoped, not creator, etc.)
   *         - 403: Permission denied (not org owner/admin)
   *         - 404: Space or organization not found
   *         - 500: Server error
   */
  async transferSpaceApiV1SpaceSpaceIdTransferPost(
    request: operations.TransferSpaceApiV1SpaceSpaceIdTransferPostRequest,
    options?: RequestOptions,
  ): Promise<models.TransferSpaceResponse> {
    return unwrapAsync(spaceTransferSpaceApiV1SpaceSpaceIdTransferPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space Children
   *
   * @remarks
   * Get all child spaces of a given space
   */
  async getSpaceChildrenApiV1SpaceSpaceIdChildrenGet(
    request: operations.GetSpaceChildrenApiV1SpaceSpaceIdChildrenGetRequest,
    options?: RequestOptions,
  ): Promise<Array<models.SubSpaceDisplayData>> {
    return unwrapAsync(spaceGetSpaceChildrenApiV1SpaceSpaceIdChildrenGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space Parent
   *
   * @remarks
   * Get the parent space of a given space
   */
  async getSpaceParentApiV1SpaceSpaceIdParentGet(
    request: operations.GetSpaceParentApiV1SpaceSpaceIdParentGetRequest,
    options?: RequestOptions,
  ): Promise<models.GetSpaceListResponseDTO> {
    return unwrapAsync(spaceGetSpaceParentApiV1SpaceSpaceIdParentGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Detach Space From Parent
   *
   * @remarks
   * Detach a space from its parent, making it standalone
   */
  async detachSpaceFromParentApiV1SpaceSpaceIdParentDelete(
    request:
      operations.DetachSpaceFromParentApiV1SpaceSpaceIdParentDeleteRequest,
    options?: RequestOptions,
  ): Promise<models.GetSpaceListResponseDTO> {
    return unwrapAsync(spaceDetachSpaceFromParentApiV1SpaceSpaceIdParentDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Space Parent
   *
   * @remarks
   * Update the parent relationship of a space
   */
  async updateSpaceParentApiV1SpaceSpaceIdParentPatch(
    request: operations.UpdateSpaceParentApiV1SpaceSpaceIdParentPatchRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceWithRelationshipsResponse> {
    return unwrapAsync(spaceUpdateSpaceParentApiV1SpaceSpaceIdParentPatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space Hierarchy
   *
   * @remarks
   * Get the full hierarchy tree starting from a given space
   */
  async getSpaceHierarchyApiV1SpaceSpaceIdHierarchyGet(
    request: operations.GetSpaceHierarchyApiV1SpaceSpaceIdHierarchyGetRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceHierarchyItem> {
    return unwrapAsync(spaceGetSpaceHierarchyApiV1SpaceSpaceIdHierarchyGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk Update Space Parent
   *
   * @remarks
   * Bulk update parent relationship for multiple spaces
   */
  async bulkUpdateSpaceParentApiV1SpaceBulkParentPatch(
    request: models.BulkUpdateParentRequest,
    options?: RequestOptions,
  ): Promise<Array<models.SpaceWithRelationshipsResponse>> {
    return unwrapAsync(spaceBulkUpdateSpaceParentApiV1SpaceBulkParentPatch(
      this,
      request,
      options,
    ));
  }

  /**
   * Unpublish space
   *
   * @remarks
   * Mark space as draft (unpublished), preserving version history
   */
  async unpublishSpaceApiV1SpaceSpaceIdUnpublishPost(
    request: operations.UnpublishSpaceApiV1SpaceSpaceIdUnpublishPostRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(spaceUnpublishSpaceApiV1SpaceSpaceIdUnpublishPost(
      this,
      request,
      options,
    ));
  }

  /**
   * List space versions
   *
   * @remarks
   * Get all published versions of a space
   */
  async listSpaceVersionsApiV1SpaceSpaceIdVersionsGet(
    request: operations.ListSpaceVersionsApiV1SpaceSpaceIdVersionsGetRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceVersionListResponse> {
    return unwrapAsync(spaceListSpaceVersionsApiV1SpaceSpaceIdVersionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get latest published space version
   *
   * @remarks
   * Retrieve the most recent published version of a space
   */
  async getLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGet(
    request:
      operations.GetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGetRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceVersionRead> {
    return unwrapAsync(
      spaceGetLatestSpaceVersionApiV1SpaceSpaceIdVersionsLatestGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get specific space version
   *
   * @remarks
   * Retrieve a specific published version of a space
   */
  async getSpaceVersionApiV1SpaceSpaceIdVersionsVersionNumberGet(
    request:
      operations.GetSpaceVersionApiV1SpaceSpaceIdVersionsVersionNumberGetRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceVersionRead> {
    return unwrapAsync(
      spaceGetSpaceVersionApiV1SpaceSpaceIdVersionsVersionNumberGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Compare space versions
   *
   * @remarks
   * Compare two versions and see what changed
   */
  async compareSpaceVersionsApiV1SpaceSpaceIdVersionsCompareGet(
    request:
      operations.CompareSpaceVersionsApiV1SpaceSpaceIdVersionsCompareGetRequest,
    options?: RequestOptions,
  ): Promise<models.VersionComparisonResponse> {
    return unwrapAsync(
      spaceCompareSpaceVersionsApiV1SpaceSpaceIdVersionsCompareGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Rollback space to version
   *
   * @remarks
   * Restore space to a specific published version
   */
  async rollbackSpaceApiV1SpaceSpaceIdRollbackPost(
    request: operations.RollbackSpaceApiV1SpaceSpaceIdRollbackPostRequest,
    options?: RequestOptions,
  ): Promise<models.GetSpaceListResponseDTO> {
    return unwrapAsync(spaceRollbackSpaceApiV1SpaceSpaceIdRollbackPost(
      this,
      request,
      options,
    ));
  }

  /**
   * List Space Roles
   *
   * @remarks
   * List all roles for a space.
   *
   * Requires space read permissions.
   */
  async listSpaceRolesApiV1SpaceSpacesSpaceIdRolesGet(
    request: operations.ListSpaceRolesApiV1SpaceSpacesSpaceIdRolesGetRequest,
    options?: RequestOptions,
  ): Promise<Array<models.SpaceRoleRead>> {
    return unwrapAsync(spaceListSpaceRolesApiV1SpaceSpacesSpaceIdRolesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Space Role
   *
   * @remarks
   * Create a new role for a space.
   *
   * Requires space management permissions.
   */
  async createSpaceRoleApiV1SpaceSpacesSpaceIdRolesPost(
    request: operations.CreateSpaceRoleApiV1SpaceSpacesSpaceIdRolesPostRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceRoleRead> {
    return unwrapAsync(spaceCreateSpaceRoleApiV1SpaceSpacesSpaceIdRolesPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space Role
   *
   * @remarks
   * Get a specific space role by ID.
   *
   * Requires space read permissions.
   */
  async getSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdGet(
    request:
      operations.GetSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceRoleRead> {
    return unwrapAsync(spaceGetSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Space Role
   *
   * @remarks
   * Update a space role.
   *
   * Requires space management permissions.
   */
  async updateSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPut(
    request:
      operations.UpdateSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPutRequest,
    options?: RequestOptions,
  ): Promise<models.SpaceRoleRead> {
    return unwrapAsync(
      spaceUpdateSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPut(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete Space Role
   *
   * @remarks
   * Delete a space role.
   *
   * Requires space management permissions.
   */
  async deleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDelete(
    request:
      operations.DeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      spaceDeleteSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdDelete(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Assign Permission To Space Role
   *
   * @remarks
   * Assign a permission to a space role.
   *
   * Requires space management permissions.
   */
  async assignPermissionToSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPost(
    request:
      operations.AssignPermissionToSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(
      spaceAssignPermissionToSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Remove Permission From Space Role
   *
   * @remarks
   * Remove a permission from a space role.
   *
   * Requires space management permissions.
   */
  async removePermissionFromSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPermissionIdDelete(
    request:
      operations.RemovePermissionFromSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPermissionIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      spaceRemovePermissionFromSpaceRoleApiV1SpaceSpacesSpaceIdRolesRoleIdPermissionsPermissionIdDelete(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get User Space Roles
   *
   * @remarks
   * Get all space roles for a user in a specific space.
   *
   * Requires space read permissions.
   */
  async getUserSpaceRolesApiV1SpaceSpacesSpaceIdMembersUserIdRolesGet(
    request:
      operations.GetUserSpaceRolesApiV1SpaceSpacesSpaceIdMembersUserIdRolesGetRequest,
    options?: RequestOptions,
  ): Promise<Array<{ [k: string]: any }>> {
    return unwrapAsync(
      spaceGetUserSpaceRolesApiV1SpaceSpacesSpaceIdMembersUserIdRolesGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Assign User To Space Role
   *
   * @remarks
   * Assign a user to a space role.
   *
   * Requires space member management permissions.
   */
  async assignUserToSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesPost(
    request:
      operations.AssignUserToSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(
      spaceAssignUserToSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Remove User From Space Role
   *
   * @remarks
   * Remove a user from a space role.
   *
   * Requires space member management permissions.
   */
  async removeUserFromSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesSpaceRoleIdDelete(
    request:
      operations.RemoveUserFromSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesSpaceRoleIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      spaceRemoveUserFromSpaceRoleApiV1SpaceSpacesSpaceIdMembersUserIdRolesSpaceRoleIdDelete(
        this,
        request,
        options,
      ),
    );
  }
}
