/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { spaceDocumentsAddDocumentToSpaceApiV1SpacesSpaceIdDocumentsDocumentIdPost } from "../funcs/space-documents-add-document-to-space-api-v1-spaces-space-id-documents-document-id-post.js";
import { spaceDocumentsGetSpaceDocumentsApiV1SpacesSpaceIdDocumentsGet } from "../funcs/space-documents-get-space-documents-api-v1-spaces-space-id-documents-get.js";
import { spaceDocumentsRemoveDocumentFromSpaceApiV1SpacesSpaceIdDocumentsDocumentIdDelete } from "../funcs/space-documents-remove-document-from-space-api-v1-spaces-space-id-documents-document-id-delete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SpaceDocuments extends ClientSDK {
  /**
   * Add Document To Space
   *
   * @remarks
   * Associate a document with a space.
   */
  async addDocumentToSpaceApiV1SpacesSpaceIdDocumentsDocumentIdPost(
    request:
      operations.AddDocumentToSpaceApiV1SpacesSpaceIdDocumentsDocumentIdPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(
      spaceDocumentsAddDocumentToSpaceApiV1SpacesSpaceIdDocumentsDocumentIdPost(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Remove Document From Space
   *
   * @remarks
   * Remove a document from a space.
   */
  async removeDocumentFromSpaceApiV1SpacesSpaceIdDocumentsDocumentIdDelete(
    request:
      operations.RemoveDocumentFromSpaceApiV1SpacesSpaceIdDocumentsDocumentIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      spaceDocumentsRemoveDocumentFromSpaceApiV1SpacesSpaceIdDocumentsDocumentIdDelete(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Space Documents
   *
   * @remarks
   * Get all documents for a space.
   */
  async getSpaceDocumentsApiV1SpacesSpaceIdDocumentsGet(
    request: operations.GetSpaceDocumentsApiV1SpacesSpaceIdDocumentsGetRequest,
    options?: RequestOptions,
  ): Promise<Array<string>> {
    return unwrapAsync(
      spaceDocumentsGetSpaceDocumentsApiV1SpacesSpaceIdDocumentsGet(
        this,
        request,
        options,
      ),
    );
  }
}
