/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { spaceDocumentsAdd } from "../funcs/space-documents-add.js";
import { spaceDocumentsGet } from "../funcs/space-documents-get.js";
import { spaceDocumentsRemove } from "../funcs/space-documents-remove.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SpaceDocuments extends ClientSDK {
  /**
   * Add Document To Space
   *
   * @remarks
   * Associate a document with a space.
   */
  async add(
    request:
      operations.AddDocumentToSpaceApiV1SpacesSpaceIdDocumentsDocumentIdPostRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(spaceDocumentsAdd(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove Document From Space
   *
   * @remarks
   * Remove a document from a space.
   */
  async remove(
    request:
      operations.RemoveDocumentFromSpaceApiV1SpacesSpaceIdDocumentsDocumentIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(spaceDocumentsRemove(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Space Documents
   *
   * @remarks
   * Get all documents for a space.
   */
  async get(
    request: operations.GetSpaceDocumentsApiV1SpacesSpaceIdDocumentsGetRequest,
    options?: RequestOptions,
  ): Promise<Array<string>> {
    return unwrapAsync(spaceDocumentsGet(
      this,
      request,
      options,
    ));
  }
}
