/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventGetTimezoneInfoApiV1EventTimezonesGet } from "../funcs/event-get-timezone-info-api-v1-event-timezones-get.js";
import { eventValidateTimezoneApiV1EventTimezonesValidateGet } from "../funcs/event-validate-timezone-api-v1-event-timezones-validate-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Timezones extends ClientSDK {
  /**
   * Get Timezone Info
   *
   * @remarks
   * Get timezone information for frontend validation and suggestions.
   *
   * Returns:
   *     Dictionary containing:
   *     - all_timezones: List of all valid IANA timezones
   *     - common_timezones: List of commonly used timezones for UI suggestions
   *     - count: Total number of supported timezones
   */
  async getTimezoneInfoApiV1EventTimezonesGet(
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(eventGetTimezoneInfoApiV1EventTimezonesGet(
      this,
      options,
    ));
  }

  /**
   * Validate Timezone
   *
   * @remarks
   * Validate a specific timezone string.
   *
   * Args:
   *     timezone: Timezone string to validate (query parameter)
   *
   * Returns:
   *     Dictionary containing:
   *     - valid: Boolean indicating if timezone is valid
   *     - timezone: The validated timezone string
   *     - suggestions: List of similar timezones if invalid (empty if valid)
   */
  async validateTimezoneApiV1EventTimezonesValidateGet(
    request: operations.ValidateTimezoneApiV1EventTimezonesValidateGetRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(eventValidateTimezoneApiV1EventTimezonesValidateGet(
      this,
      request,
      options,
    ));
  }
}
