"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .linebundleerror import LinebundleError
from typing import Any, TYPE_CHECKING

from linebundle_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .httpvalidationerror import HTTPValidationError, HTTPValidationErrorData
    from .linebundledefaulterror import LinebundleDefaultError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "HTTPValidationError",
    "HTTPValidationErrorData",
    "LinebundleDefaultError",
    "LinebundleError",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "HTTPValidationError": ".httpvalidationerror",
    "HTTPValidationErrorData": ".httpvalidationerror",
    "LinebundleDefaultError": ".linebundledefaulterror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
